import {
  CombatExtraSpellAction,
  CombatUnitClass,
  ICombatUnit,
  LogEvent,
} from "@gladlog/parser-compat";

import {
  BREAK_RACIAL_SPELL_IDS,
  racialName,
  SHARED_CD_RACIAL_SPELL_IDS,
  TRINKET_RACIAL_SHARED_LOCKOUT_MS,
} from "../data/racialAbilities";
import { getEnglishSpellName, kickLockoutSeconds } from "../data/spellEffectData";
import {
  immunityCoversSpell,
  isPhysicalSpell,
  spellSchoolMask,
} from "../data/spellSchools";
import { ccSpellIds, disarmSpellIds, rootSpellIds } from "../data/spellTags";
import trinketItemIdsData from "../data/trinketItemIds.json";
import { isHealerSpec, specToString } from "./cooldowns";
import { computeIncomingDR, IDRInfo, matchPendingCcKey } from "./drAnalysis";
import {
  distanceBetween,
  getUnitPositionAtTime,
  hasLineOfSight,
} from "./losAnalysis";
import {
  CC_MAX_PLAUSIBLE_RANGE_YARDS,
  INTERP_MAX_GAP_MS,
} from "./positionSampling";
import { fmtTime } from "./renderGrid";
import { getTalentAvoidanceBuffs } from "./talentBehaviors";
import { DPS_TRINKET_CD_S, HEALER_TRINKET_CD_S } from "./trinketCooldown";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/** Gladiator's Medallion — active PvP trinket that breaks CC */
const GLADIATOR_TRINKET_SPELL_ID = "336126";
/** Adaptation — passive auto-break trinket (proc spell) */
const ADAPTATION_TRINKET_SPELL_ID = "195756";

/** Item IDs for Relentless (passive DR, no active) — generated by start:generateTrinketItemIds */
const RELENTLESS_ITEM_IDS = new Set<string>(
  trinketItemIdsData.relentlessItemIds,
);
/** Item IDs for Adaptation (auto-break on 5s CC, no manual cast) — generated by start:generateTrinketItemIds */
const ADAPTATION_ITEM_IDS = new Set<string>(
  trinketItemIdsData.adaptationItemIds,
);

/**
 * Window in ms within which a trinket cast is considered a direct response
 * to a CC application (applied then trinket used within this window).
 *
 * GH #34 batch 4 (2026-08-28), 300 matches / 3,130 trinket uses with a prior
 * CC: latency from the nearest prior CC — < 1 s 1,469 · 1–2 s 1,165 · 2–3 s 142
 * · 3–5 s 79 · 5–8 s 39 · 8–15 s 54 · ≥ 15 s 182 (p50 1.0 s, p90 3.6 s,
 * 91.2 % ≤ 5 s). The 5 s cut sits in the sparse tail after the 2 s mass, so
 * moving it ±2 s reclassifies < 4 % of uses. Measured, not official.
 */
const TRINKET_RESPONSE_WINDOW_MS = 5000;

/**
 * Minimum damage taken during a CC window for it to be considered a meaningful
 * missed trinket opportunity.
 *
 * GH #34 batch 4 (2026-08-28), same corpus, 10,322 `available_unused` CC
 * instances: damageTakenDuring < 10 k 4,746 · 10–20 k 1,051 · 20–30 k 798 ·
 * 30–50 k 1,085 · 50–100 k 1,156 · ≥ 100 k 1,486 (p50 13.6 k, p75 51.8 k,
 * p90 145 k). Share kept as "missed trinket": ≥ 20 k 43.8 % · **≥ 30 k
 * 36.1 %** · ≥ 50 k 25.6 % — a smooth region with no natural break, so the
 * threshold is an editorial cut on a continuum. (CCs where the trinket WAS
 * used show p50 2.7 k — the comparison is confounded by the trinket itself
 * cutting the window short.) Re-run the distribution before moving it.
 */
const SIGNIFICANT_CC_DAMAGE = 30_000;

// Position snapshots are event-driven; beyond this gap to the nearest snapshot
// the interpolated position is fabricated (unit idle/stealthed — worst in openers).
// T3 grounding guard: 8s allowed linear interpolation through the middle of a
// stealth/teleport sampling gap, fabricating positions that never existed (a
// full-corpus scan proved 16 fake distances, with a melee Cheap Shot labelled
// 17-21yd). Queries near either edge, within 1.5s, remain valid; the middle of a
// gap is always suppressed (better to make no claim than a false one).
const CC_POSITION_MAX_GAP_MS = INTERP_MAX_GAP_MS;
// A recomputed distance above CC_MAX_PLAUSIBLE_RANGE_YARDS is bad data and that
// distance is suppressed (100-match scan: 0:06 Sap "64.7yd", 0:11 Sleep Walk
// "54.7yd"). The threshold itself is a single-source export from
// positionSampling — the positioningScan gate's G6 imports the same number to
// verify this contract.

/**
 * Buffs/abilities that can cause a targeted CC cast to whiff (dodge, reflect, immunity,
 * untargetable). Maps the buff's spell ID → display name shown as the avoidance reason.
 * Seasonal maintenance: update IDs here when these abilities change.
 */
// Baseline (non-PvP-talent) immunity / reflect / untargetable buffs. NOTE: Fade (586) is intentionally NOT
// here — baseline Fade only drops threat. Talent-granted avoidance buffs (Phase Shift, the Shrouds, Blessing
// of Spellwarding, Peaceweaver, …) live in the B139 talentBehaviors catalog and are merged in below, so that
// catalog is the single source for PvP-talent behavior.
// DEFENSIVE-001 (2026-08-07, BACKLOG #18 second batch): exported so both the
// one-off occurrence-rate probe (packages/desktop/scripts/tmp-defensive-rates.mts,
// evaluated then deleted) and the real cc-avoidable candidate
// (candidateFindings.ts, via applicableCCAvoidanceIds below) consume this
// module's real avoidance table instead of hand-copying spell IDs
// (shared-predicate rule) — no behavior change to this file's own logic,
// additive only.
// 2026-08-21 S2 corpus scan (10,682 matches): removed old Bladestorm 389774 (227847 is the live cast id) — 0 occurrences, ability gone in 12.x (eval-private/reports/s2-health-2026-08-21)
// 2026-08-23 completeness pass — the first one this table ever had ground truth
// for: `SPELL_MISSED`'s missType was parsed away until today, so "the game said
// IMMUNE" was unobservable. Discriminator (immuneCcScan.ts, 1200 S2 rounds):
// immuneRate(X) = CC-immune-with-X-up / (that + CC-landed-with-X-up). Real
// immunities sit at the top (Divine Shield 100%, Ice Block 100%, Precognition
// 95.3%); ambient buffs fall out on their own (a naive "any covering buff" scan
// ranks Power Word: Fortitude first, because targets always have buffs up).
// Three same-name variant ids were missing — the aura-id-rot class: for AMS the
// listed 48707 saw 12 immunes while the unlisted 444741 saw 108.
export const CC_AVOIDANCE_BUFF_SPELLS = new Map<string, string>([
  ["377362", "Precognition"],
  ["23920", "Spell Reflection"],
  ["354610", "Glimpse"],
  ["227847", "Bladestorm"],
  ["446035", "Bladestorm"], // variant id, immuneRate 90.8% (69/7)
  ["642", "Divine Shield"],
  ["1022", "Blessing of Protection"],
  ["45438", "Ice Block"],
  ["186265", "Aspect of the Turtle"],
  ["48707", "Anti-Magic Shell"],
  ["444741", "Anti-Magic Shell"], // variant id, immuneRate 65.9% (108/56) — the DOMINANT AMS id in S2
  ["410358", "Anti-Magic Shell"], // Spellwarden (ally-cast AMS), immuneRate 54.7% (29/24)
  ["421453", "Ultimate Penitence"], // Disc channel immunity, immuneRate 64.4% (38/21); has a real 240s CD so the cast-side kit gate works too
  // ── second batch, 3,300-round scan (entries below cleared n>=25 only at that
  // scale). Every one was dest-type checked: the aura lands on PLAYERS, which
  // rules out the summon confound that disqualified Healing Stream (5672,
  // 97.8% immuneRate but the aura sits on the CC-immune totem itself — the
  // totem's immunity, not the buff's) and the creature-side Deep Breath
  // variant 1236943. The Beast Within (357140) regressed below 50% at scale
  // (51.2% at n=41 was noise) — deliberately NOT listed.
  ["433874", "Deep Breath"], // Evoker flight, unstoppable while airborne; immuneRate 93.8% (76/5)
  ["357210", "Deep Breath"], // variant id, immuneRate 85.4% (41/7)
  ["1252613", "Command Squadron"], // immuneRate 92.9% (65/5), aura on players
  ["1261393", "Command Squadron"], // variant id, immuneRate 93.8% (76/5)
  ["1261395", "Command Squadron"], // variant id, immuneRate 93.8% (76/5)
  ["410355", "Stretch Time"], // immuneRate 93.1% (67/5), aura on players
  ["443028", "Celestial Conduit"], // Monk channel immunity (same shape as Ultimate Penitence), immuneRate 62.5% (20/12); real 90s CD
]);
// B139: merge the talent-granted CC/magic-immunity avoidance buffs from the behavioral catalog. Self-gating
// (each buff aura only exists when its talent is taken). Adds Peaceweaver (353319) and Phase Shift (408558),
// Nullifying Shroud (378464), Psychic Shroud (1246965), Blessing of Spellwarding (204018).
for (const [buffId, name] of getTalentAvoidanceBuffs()) {
  CC_AVOIDANCE_BUFF_SPELLS.set(buffId, name);
}

// 2026-08-21 S2 corpus scan (10,682 matches): removed 114223 (no DB2 name) — 0 occurrences, ability gone in 12.x (eval-private/reports/s2-health-2026-08-21)
export const DRUID_FORM_BUFFS = new Map<string, string>([
  ["5487", "Bear Form"],
  ["768", "Cat Form"],
  ["783", "Travel Form"],
  ["24858", "Moonkin Form"],
]);

/** @internal exported for data/curatedIdRegistry (corpus rot scan) */
// 2026-08-21 S2 corpus scan (10,682 matches): removed Wyvern Sting 19386, Repentance 20066 — 0 occurrences, ability gone in 12.x (eval-private/reports/s2-health-2026-08-21)
export const BREAKABLE_CC_SPELL_IDS = new Set([
  "118", // Polymorph
  "51514", // Hex
  "3355", // Freezing Trap
  "5782", // Fear
  "8122", // Psychic Scream
]);

/** Shaman Grounding Totem — redirects the first targeted hostile spell. */
const GROUNDING_TOTEM_SPELL_ID = "204336"; // 2026-08-21: was 8177 (no DB2 name); 204336 = live Grounding Totem

/** Priest Shadow Word: Death — can break a freshly-applied breakable CC on the caster. */
const SHADOW_WORD_DEATH_SPELL_ID = "32379";

// 2026-08-21 S2 corpus scan (10,682 matches): removed Sigil of Silence 202137 — 0 occurrences, ability gone in 12.x (eval-private/reports/s2-health-2026-08-21)
export const GROUND_CC_SPELL_IDS = new Set<string>([
  "3355", // Freezing Trap (Hunter)
  "207684", // Sigil of Misery (Demon Hunter)
  "192058", // Capacitor Totem (Shaman)
  "30283", // Shadowfury (Warlock)
  "113724", // Ring of Frost (Mage)
]);

// Magic-only immunities block magic-school effects but NOT physical CC. Don't credit them for a
// physical CC (Kidney/Cheap Shot/Blind/etc.) they could not have prevented. (Phase Shift and
// Psychic Shroud are general untargetable / next-CC immunities, so they CAN dodge physical — excluded.)
export const MAGIC_ONLY_IMMUNITY_IDS = new Set<string>([
  "378464", // Nullifying Shroud
  "353319", // Peaceweaver
  "204018", // Blessing of Spellwarding
  "48707", // Anti-Magic Shell
  "444741", // Anti-Magic Shell (variant id — same magic-only semantics)
  "410358", // Anti-Magic Shell (Spellwarden ally-cast — same magic-only semantics)
  "23920", // Spell Reflection
]);
export const PHYSICAL_CC_IDS = new Set<string>([
  "408", // Kidney Shot
  "1833", // Cheap Shot
  "2094", // Blind
  "22570", // Maim
  "19577", // Intimidation
  "107570", // Storm Bolt
  "46968", // Shockwave
  "119381", // Leg Sweep
  "20549", // War Stomp
]);
/** Grounding Totem redirects only the FIRST targeted spell per placement; don't credit two within this window. */
// GH #34 batch 4 (2026-08-28): rendering dedupe only — collapses Grounding Totem
// redirects closer than 6 s into one [CC AVOIDED] line. No predicate or candidate
// reads it; editorial, not measured.
const GROUNDING_DEDUPE_SECONDS = 6;

export const REPOSITIONING_SPELL_IDS = new Map<string, string>([
  ["119996", "Transcendence: Transfer"],
  ["109132", "Roll"],
  ["115008", "Chi Torpedo"],
  ["116841", "Tiger's Lust"],
  ["102401", "Wild Charge"],
  ["1850", "Dash"],
  ["106898", "Stampeding Roar"],
  ["190784", "Divine Steed"],
  ["1044", "Blessing of Freedom"],
  ["58875", "Spirit Walk"],
  ["192082", "Gust of Wind"],
  ["192077", "Wind Rush Totem"],
  ["2645", "Ghost Wolf"],
  ["358267", "Hover"],
  ["370665", "Rescue"],
  ["121536", "Angel's Feather"],
  ["58984", "Shadowmeld"],
  ["5487", "Bear Form"],
  ["768", "Cat Form"],
  ["783", "Travel Form"],
  ["24858", "Moonkin Form"],
]);

export const TARGETED_CC_DODGE_SPELLS = new Set<string>([
  "119996", // Transcendence: Transfer
  "58984", // Shadowmeld
]);

/** @internal exported for data/curatedIdRegistry (corpus rot scan) */
export const TREMOR_BREAKABLE_CC_IDS = new Set<string>([
  "5782", // Fear
  "8122", // Psychic Scream
  "5484", // Howl of Terror
]);

/**
 * DEFENSIVE-001 (cc-avoidable, 2026-08-07, BACKLOG #18 second batch): pure
 * derivation of "which avoidance spell ids would explain dodging this CC
 * application" — the identical gating rules the CC Avoidance Correlation
 * sweep below applies inline while deciding `ccAvoidedInstances` (buff
 * school gate: a magic-only immunity cannot explain a physical CC; Druid
 * forms only credited for Polymorph/Hex, never a ground CC or another
 * targeted CC; mobility credited for any ground CC, or a targeted CC only
 * via TARGETED_CC_DODGE_SPELLS). Extracted as its own exported pure function
 * — rather than re-derived a second time in candidateFindings.ts — because
 * cc-avoidable asks a different question of the SAME predicate: not "was
 * this CC avoided" (ccAvoidedInstances, computed from what actually
 * happened), but "for a CC that landed, which of these tools WOULD have
 * applied" (a hypothetical the inline sweep never needs to ask, because it
 * only runs for CCs that were NOT credited with an avoidance). Shared-
 * predicate rule (CLAUDE.md): the gating logic for "which avoidance ids
 * apply to this CC" lives in exactly one place; both call sites (this
 * function and the inline sweep) must be read together when either changes.
 * Additive: this function is never called from the inline sweep above, so it
 * changes zero existing behavior.
 */
export function applicableCCAvoidanceIds(
  ccSpellId: string,
  ccSpellName: string,
): Set<string> {
  const out = new Set<string>();
  const isGroundCC = GROUND_CC_SPELL_IDS.has(ccSpellId);
  const isPolyOrHex = /polymorph|hex/i.test(ccSpellName);

  // A. Buff-based avoidance. 官方优先(GH #29 阶段 1):学派掩码知道两边时直接
  // 判定「这个免疫挡不挡得住这个控」;官方缺数据时才回退到原来的手工单向规则。
  //
  // 原规则只有一个方向 —— 「纯魔法免疫挡不住物理控」—— 没有反向,于是**纯物理
  // 免疫被推荐去躲魔法控**:250 场实测 2 条建议用保护祝福(SCHOOL_IMMUNITY 掩码
  // = 1,仅物理)躲 Sleep Walk(SchoolMask = 8,自然系)。
  //
  // 回退分支里 CC 的「是不是物理」也改问官方(`isPhysicalSpell`),手工的
  // PHYSICAL_CC_IDS 只在官方没有该 id 时兜底:那 9 条本身没写错,但漏了制裁之锤
  // (神圣)、暗影之怒(暗影)、混沌新星(多学派)这些魔法控 —— 手工名单证不了全。
  for (const buffId of CC_AVOIDANCE_BUFF_SPELLS.keys()) {
    const covers = immunityCoversSpell(buffId, ccSpellId);
    if (covers === false) continue; // 官方判定:挡不住
    if (covers === undefined) {
      // 官方缺这个免疫的 aura39 行(反魔法护罩/法术反射/剑刃风暴/龟盾…)
      const ccIsPhysical =
        isPhysicalSpell(ccSpellId) ?? PHYSICAL_CC_IDS.has(ccSpellId);
      if (MAGIC_ONLY_IMMUNITY_IDS.has(buffId) && ccIsPhysical) continue;
    }
    out.add(buffId);
  }
  if (isPolyOrHex) {
    for (const formId of DRUID_FORM_BUFFS.keys()) out.add(formId);
  }
  // B. Mobility-based avoidance: any repositioning spell dodges a ground CC;
  // only the TARGETED_CC_DODGE_SPELLS subset dodges a targeted CC. Druid
  // forms never count here (H14: shapeshifting does not reposition the
  // player out of a ground AoE, and the buff branch above already handles
  // their Polymorph/Hex-only case).
  for (const moveId of REPOSITIONING_SPELL_IDS.keys()) {
    if (DRUID_FORM_BUFFS.has(moveId)) continue;
    if (isGroundCC || TARGETED_CC_DODGE_SPELLS.has(moveId)) out.add(moveId);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export type TrinketType = "Gladiator" | "Adaptation" | "Relentless" | "Unknown";

export interface ICCInstance {
  atSeconds: number;
  durationSeconds: number;
  spellId: string;
  spellName: string;
  sourceName: string;
  sourceSpec: string;
  damageTakenDuring: number;
  /**
   * `racial_break` (2026-08-12): the CC was removed by a racial that does what
   * the PvP trinket does (Every Man for Himself, Will of the Forsaken, …).
   * It is deliberately NOT folded into `used` — the trinket itself was not
   * pressed, and prompts render this state verbatim, so calling it "used"
   * would state something the log does not say. What it must never be is
   * `available_unused`: the player did break out, and 35 of 2730
   * available-unused windows across 120 local matches were exactly this
   * (measured before the fix).
   */
  trinketState:
    | "used"
    | "racial_break"
    | "available_unused"
    | "on_cooldown"
    | "passive_trinket";
  /** Which racial removed it. Only set when trinketState === "racial_break". */
  breakRacialName?: string;
  /** Seconds until trinket is ready again. Only populated when trinketState === 'on_cooldown'. */
  trinketCDSecondsLeft?: number;
  /** DR state at the time this CC was applied. null if spell not in DR category map. */
  drInfo: IDRInfo | null;
  /**
   * Distance in yards between caster and target at the moment of CC application.
   * null when advanced logging is absent.
   */
  distanceYards: number | null;
  /**
   * Whether the caster had unobstructed line of sight to the target.
   * null when arena geometry is not mapped or advanced logging is absent.
   */
  losBlocked: boolean | null;
}

export interface IRootInstance {
  atSeconds: number;
  durationSeconds: number;
  spellId: string;
  spellName: string;
  sourceName: string;
  sourceSpec: string;
}

/** BACKLOG #36(b): what the player did in the `POST_KICK_WINDOW_S` after
 * eating a kick. The lockout duration itself carries no information (840
 * corpus kicks all land in 3–4s — modern school lockouts are fixed), so the
 * teachable severity axis is the BEHAVIOR while locked:
 *   - "switched": cast something whose official school mask shares no bits
 *     with the interrupted spell's
 *   - "acted": cast something, but same/unknown school (waited the lockout
 *     out, or masks unavailable — three-state data, never guessed)
 *   - "idle": zero casts for the whole window — the paralysis case
 *
 * ⚠ **"switched" is NOT "kept playing through the lockout"** — that reading
 * was in this comment until 2026-09-06 and it is wrong. The test is a school
 * mask, not a hardcast, so ANY cast qualifies: measured over 400 corpus
 * rounds, only 16/292 switches had their own `SPELL_CAST_START`; the rest
 * were instants — Cat Form, Hover, Will to Survive, even the PvP trinket
 * (`packages/eval/scripts/postKickSwitchAudit.ts`). Downstream text must
 * therefore name the cast and qualify it (`switchSpellName` /
 * `switchWasHardCast`) rather than assert the player kept casting.
 *
 * The same correction applies to the corpus anchor below: what it measured
 * is the rate of pressing ANY off-school ability, not of casting through a
 * lockout, so **it does not support a severity ordering on its own**. Left
 * here because the rate itself is real and reproducible.
 *
 * Corpus anchor (500 matches, healer-study school_probe): switch rates track
 * spec kit ceilings (Disc 76–80% vs Holy Paladin 8%), so cross-spec
 * comparison is kit × skill; within-spec, the idle rate is the coachable
 * half. */
export type PostKickBehavior = "switched" | "acted" | "idle";

export interface IInterruptInstance {
  atSeconds: number;
  lockoutDurationSeconds: number;
  kickSpellId: string;
  kickSpellName: string;
  interruptedSpellId: string;
  interruptedSpellName: string;
  sourceName: string;
  sourceSpec: string;
  postKick: PostKickBehavior;
  /** Seconds until the first cast after the kick; null when idle. */
  firstActionDelayS: number | null;
  /** `switched` only: the cast that actually made the classification
   * "switched" — the first one in the window on a disjoint school. It is NOT
   * always `firstActionDelayS`'s cast: a same-school cast can come first
   * (measured 2026-09-06 on match 825ca842 — first cast 0.5s, the disjoint
   * one 2.0s), so the rendered line must pair the school claim with THIS
   * cast's own delay or it welds two different casts into one sentence. */
  switchSpellName: string | null;
  /** Seconds from the kick to `switchSpellName`'s cast. */
  switchDelayS: number | null;
  /** Whether that cast had its own `SPELL_CAST_START` — i.e. it was a real
   * hardcast rather than an instant.
   *
   * **Three-state on purpose.** `castStartEvents` is optional on archived
   * docs (`parser-compat/src/types.ts`), and `parser-compat` exposes NO
   * channel events at all, so a channelled cast is indistinguishable from an
   * instant. `true` = a CAST_START was found; `false` = the field was
   * populated and no CAST_START matched (instant OR channel); `null` = no
   * cast-start data for this unit, nothing may be claimed either way.
   *
   * Why this exists (2026-09-06 audit, packages/eval/scripts/
   * postKickSwitchAudit.ts): the `switched` classification only requires a
   * disjoint school mask, not a hardcast, so 276/292 corpus switches were
   * triggered by an instant — Cat Form, Hover, Will to Survive, even the PvP
   * trinket — while the prompt asserted "kept playing through the lockout".
   * The classification itself is unchanged; only what the line may CLAIM is. */
  switchWasHardCast: boolean | null;
}

export interface ICCAvoidedInstance {
  atSeconds: number;
  spellId: string;
  spellName: string;
  avoidanceSpellName: string;
  avoidanceSpellId: string;
  sourceName: string;
  sourceSpec: string;
}

/** BACKLOG #36(b): how long after a kick the player's behavior is judged.
 * 5s = the research criterion (healer-study school_probe, 500 matches): it
 * straddles the fixed 3–4s lockout, so "idle" is damning — nothing was cast
 * even once the lockout ended. */
export const POST_KICK_WINDOW_S = 5;

/** How far before a `SPELL_CAST_SUCCESS` its own `SPELL_CAST_START` may sit
 * when deciding `switchWasHardCast`. The longest arena hardcasts are ~3s;
 * 6s is deliberately generous, so the only error this can make is calling an
 * instant a hardcast — the conservative direction for a line whose whole
 * point is not to over-claim "kept casting". */
export const CAST_START_LOOKBACK_S = 6;

export interface IPlayerCCTrinketSummary {
  playerName: string;
  playerSpec: string;
  trinketType: TrinketType;
  trinketCooldownSeconds: number;
  ccInstances: ICCInstance[];
  trinketUseTimes: number[]; // atSeconds for each trinket cast
  /** CC windows where trinket was available but player didn't use it, with significant damage */
  missedTrinketWindows: ICCInstance[];
  /** Roots applied by enemies. No DR category. */
  rootInstances: IRootInstance[];
  /** Disarms applied by enemies. No DR category. */
  disarmInstances: IRootInstance[];
  /** Kicks (interrupts) landed by enemies. */
  interruptInstances: IInterruptInstance[];
  /** CC avoidance/mitigation/breaks. Always populated by analyzePlayerCCAndTrinket
   * (empty array when none) — part of the summary contract. */
  ccAvoidedInstances: ICCAvoidedInstance[];
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Render a CC instance's trinket state for model-facing facts. Single source
 * for candidateFindings (cc-locked) and deepDive, so the two cannot describe
 * the same fact differently: `racial_break` must name the racial, because the
 * bare enum tells the model nothing and "used" would be a lie about the
 * trinket.
 */
export function trinketStateFact(
  cc: Pick<ICCInstance, "trinketState" | "breakRacialName">,
): string {
  return cc.trinketState === "racial_break"
    ? `broken_by_racial(${cc.breakRacialName ?? "unknown"})`
    : cc.trinketState;
}

export function detectTrinketType(unit: ICombatUnit): TrinketType {
  const trinketSlots = (unit.info?.equipment ?? []).filter((_, i) =>
    [12, 13].includes(i),
  );
  if (trinketSlots.some((e) => RELENTLESS_ITEM_IDS.has(e.id)))
    return "Relentless";
  if (trinketSlots.some((e) => ADAPTATION_ITEM_IDS.has(e.id)))
    return "Adaptation";
  if (trinketSlots.length > 0) return "Gladiator";
  return "Unknown";
}

/**
 * Returns all timestamps (ms) at which the unit successfully cast their active trinket.
 */
function getTrinketCastTimestamps(
  unit: ICombatUnit,
  trinketType: TrinketType,
): number[] {
  if (trinketType === "Relentless") return []; // passive, never cast
  const spellId =
    trinketType === "Adaptation"
      ? ADAPTATION_TRINKET_SPELL_ID
      : GLADIATOR_TRINKET_SPELL_ID;
  return unit.spellCastEvents
    .filter(
      (e) =>
        e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
        e.spellId === spellId,
    )
    .map((e) => e.logLine.timestamp);
}

/**
 * Milliseconds until the trinket is ready again at `atMs`, or 0 when it is
 * available. Two independent locks apply and the later one wins:
 *
 *  1. the trinket's own cooldown after the player pressed it, and
 *  2. the shared lockout a category-1166 racial imposes (2026-08-12) — press
 *     Will of the Forsaken and the medallion is locked for
 *     TRINKET_RACIAL_SHARED_LOCKOUT_MS, which the ledger used to ignore
 *     entirely, so 57 of 2695 "trinket in hand, sat in it" windows across 120
 *     local matches blamed the player for a button the game had taken away.
 *
 * Returning the remaining time rather than a boolean keeps `on_cooldown`'s
 * "Ns left" honest for both causes — a caller that recomputed the remainder
 * from trinket casts alone would print a wrong number for the racial lock.
 */
function trinketCooldownRemainingMs(
  castTimestamps: number[],
  cooldownMs: number,
  racialLockTimestamps: number[],
  atMs: number,
): number {
  const remainingFrom = (timestamps: number[], lockMs: number): number => {
    let last = -Infinity;
    for (const ts of timestamps) {
      if (ts <= atMs) last = ts;
      else break;
    }
    if (last === -Infinity) return 0;
    return Math.max(0, lockMs - (atMs - last));
  };
  return Math.max(
    remainingFrom(castTimestamps, cooldownMs),
    remainingFrom(racialLockTimestamps, TRINKET_RACIAL_SHARED_LOCKOUT_MS),
  );
}

// ---------------------------------------------------------------------------
// Main analysis
// ---------------------------------------------------------------------------

export function analyzePlayerCCAndTrinket(
  player: ICombatUnit,
  enemies: ICombatUnit[],
  combat: { startTime: number; endTime: number; startInfo: { zoneId: string } },
  // 2026-07-18 baseline investigation: CC from enemy pets (Intimidation,
  // Seduction, …) used to be silently dropped by the "src ∈ enemy players"
  // filter (Intimidation missing in 54/176 matches) — leaving [CC ON TEAM],
  // trinket windows and DR chains all blind downstream. The caller passes enemy
  // pet units in to complete the src set.
  enemyPets: ICombatUnit[] = [],
): IPlayerCCTrinketSummary {
  const enemyIds = new Set([...enemies, ...enemyPets].map((u) => u.id));
  const matchStartMs = combat.startTime;

  const trinketType = detectTrinketType(player);
  const isHealer = isHealerSpec(player.spec);
  const trinketCooldownSeconds = isHealer
    ? HEALER_TRINKET_CD_S
    : DPS_TRINKET_CD_S;
  const trinketCooldownMs = trinketCooldownSeconds * 1000;

  const trinketCastTimestamps = getTrinketCastTimestamps(
    player,
    trinketType,
  ).sort((a, b) => a - b);

  // Build a map of CC apply → remove timestamps for this player from enemies
  // spellId → list of { applyMs, removeMs }
  const ccWindows: Array<{
    spellId: string;
    spellName: string;
    srcName: string;
    srcUnitId: string;
    applyMs: number;
    removeMs: number;
  }> = [];

  const pendingCC = new Map<
    string,
    { applyMs: number; spellName: string; srcName: string; srcUnitId: string }
  >();

  const pendingRoot = new Map<
    string,
    { applyMs: number; spellName: string; srcId: string; srcName: string }
  >();
  const rootWindows: Array<{
    spellId: string;
    spellName: string;
    srcId: string;
    srcName: string;
    applyMs: number;
    removeMs: number;
  }> = [];

  const pendingDisarm = new Map<
    string,
    { applyMs: number; spellName: string; srcId: string; srcName: string }
  >();
  const disarmWindows: Array<{
    spellId: string;
    spellName: string;
    srcId: string;
    srcName: string;
    applyMs: number;
    removeMs: number;
  }> = [];

  for (const aura of player.auraEvents) {
    const spellId = aura.spellId;
    if (!spellId) continue;
    const isRemovalEvent =
      aura.logLine.event === LogEvent.SPELL_AURA_REMOVED ||
      aura.logLine.event === LogEvent.SPELL_AURA_BROKEN ||
      aura.logLine.event === LogEvent.SPELL_AURA_BROKEN_SPELL;
    // The caster filter applies to apply/refresh only: removals (especially
    // BROKEN, whose src is the breaker) must NOT be dropped by src — a broken CC
    // that never closes inflates its duration all the way to match end (fixed
    // 2026-08-02; the pairing semantics live in the single source
    // matchPendingCcKey).
    if (!isRemovalEvent && !enemyIds.has(aura.srcUnitId)) continue;

    if (rootSpellIds.has(spellId) || disarmSpellIds.has(spellId)) {
      const isRoot = rootSpellIds.has(spellId);
      const pending = isRoot ? pendingRoot : pendingDisarm;
      const windows = isRoot ? rootWindows : disarmWindows;
      const key = `${spellId}:${aura.srcUnitId}`;
      const event = aura.logLine.event;

      if (event === LogEvent.SPELL_AURA_APPLIED) {
        pending.set(key, {
          applyMs: aura.timestamp,
          spellName: getEnglishSpellName(spellId, aura.spellName),
          srcId: aura.srcUnitId,
          srcName: aura.srcUnitName,
        });
      } else if (isRemovalEvent) {
        const matchKey = matchPendingCcKey(pending, spellId, key);
        const p = matchKey ? pending.get(matchKey) : undefined;
        if (p && matchKey) {
          windows.push({
            spellId,
            spellName: p.spellName,
            srcId: p.srcId,
            srcName: p.srcName,
            applyMs: p.applyMs,
            removeMs: aura.timestamp,
          });
          pending.delete(matchKey);
        }
      }
    }

    const isBacklashPossible = spellId === "196364" || spellId === "34914"; // 2026-08-21: 196363 (dead) → 196364 live UA backlash silence
    if (!ccSpellIds.has(spellId) && !isBacklashPossible) continue;

    // FIX 2: key by spellId+caster so re-applications from the same caster don't
    // overwrite the pending entry before the first removal fires.
    const ccKey = `${spellId}:${aura.srcUnitId}`;
    const event = aura.logLine.event;
    if (event === LogEvent.SPELL_AURA_APPLIED) {
      pendingCC.set(ccKey, {
        applyMs: aura.timestamp,
        spellName: getEnglishSpellName(spellId, aura.spellName),
        srcName: aura.srcUnitName,
        srcUnitId: aura.srcUnitId,
      });
    } else if (isRemovalEvent) {
      const matchKey = matchPendingCcKey(pendingCC, spellId, ccKey);
      const pending = matchKey ? pendingCC.get(matchKey) : undefined;
      if (pending && matchKey) {
        ccWindows.push({
          spellId,
          spellName: pending.spellName,
          srcName: pending.srcName,
          srcUnitId: pending.srcUnitId,
          applyMs: pending.applyMs,
          removeMs: aura.timestamp,
        });
        pendingCC.delete(matchKey);
      }
    }
  }

  // Close any CCs still pending at match end
  Array.from(pendingCC.entries()).forEach(([ccKey, pending]) => {
    const [pendingSpellId] = ccKey.split(":");
    ccWindows.push({
      spellId: pendingSpellId,
      spellName: pending.spellName,
      srcName: pending.srcName,
      srcUnitId: pending.srcUnitId,
      applyMs: pending.applyMs,
      removeMs: combat.endTime,
    });
  });

  for (const [key, p] of pendingRoot) {
    const [pendingSpellId] = key.split(":");
    rootWindows.push({
      spellId: pendingSpellId,
      spellName: p.spellName,
      srcId: p.srcId,
      srcName: p.srcName,
      applyMs: p.applyMs,
      removeMs: combat.endTime,
    });
  }
  for (const [key, p] of pendingDisarm) {
    const [pendingSpellId] = key.split(":");
    disarmWindows.push({
      spellId: pendingSpellId,
      spellName: p.spellName,
      srcId: p.srcId,
      srcName: p.srcName,
      applyMs: p.applyMs,
      removeMs: combat.endTime,
    });
  }

  // Resolve source spec from enemies list
  const enemySpecMap = new Map(
    enemies.map((u) => [u.id, specToString(u.spec)]),
  );
  const enemyUnitMap = new Map(enemies.map((u) => [u.id, u]));
  const zoneId = combat.startInfo.zoneId;

  // Build ICCInstance list (without drInfo — computed after sort)
  const filteredCCWindows = ccWindows.filter((w) => {
    if (w.spellId === "34914") {
      const durationS = (w.removeMs - w.applyMs) / 1000;
      return durationS <= 4; // Horror is 3s; DoT is 21s
    }
    return true;
  });

  // B111: bind each trinket cast to the SINGLE CC it actually broke, instead of tagging
  // every CC that landed within 5s of the cast. An active PvP trinket (Gladiator's Medallion
  // / Adaptation) removes loss-of-control, so it can only break a CC that was still ACTIVE at
  // the cast instant (applyMs ≤ castTs ≤ removeMs). The old window mis-tagged CCs that had
  // already expired before the trinket press, so the coach blamed a trivial / DR'd-to-0 CC
  // rather than the real one. When several CCs are active at once, credit the longest-active.
  const TRINKET_BREAK_TOLERANCE_MS = 250;
  /** Bind one break cast to the single CC it broke (shared by the trinket and
   * the racial pass, so the two can never drift apart). */
  const bindBreakToWindow = (castTs: number): number => {
    let primaryIdx = -1;
    let primaryDurationMs = -1;
    filteredCCWindows.forEach((w, idx) => {
      const activeAtCast =
        castTs >= w.applyMs - TRINKET_BREAK_TOLERANCE_MS &&
        castTs <= w.removeMs + TRINKET_BREAK_TOLERANCE_MS;
      if (!activeAtCast) return;
      const durationMs = w.removeMs - w.applyMs;
      if (durationMs > primaryDurationMs) {
        primaryDurationMs = durationMs;
        primaryIdx = idx;
      }
    });
    return primaryIdx;
  };
  const trinketBrokenWindowIdx = new Set<number>();
  for (const trinketTs of trinketCastTimestamps) {
    const idx = bindBreakToWindow(trinketTs);
    if (idx >= 0) trinketBrokenWindowIdx.add(idx);
  }

  // Racial breaks (2026-08-12): the log has no race field, so ownership is
  // established purely by observing the cast — which is all this needs. Bound
  // through the same predicate as the trinket, so a CC the player actually
  // escaped can never be reported as "trinket in hand, sat in it".
  const racialBrokenWindow = new Map<number, string>();
  /** Casts that lock the PvP trinket through the shared category (sorted, so
   * trinketCooldownRemainingMs can scan them the same way as trinket casts). */
  const racialLockTimestamps: number[] = [];
  for (const e of player.spellCastEvents) {
    if (e.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
    const id = e.spellId;
    if (id && SHARED_CD_RACIAL_SPELL_IDS.has(id))
      racialLockTimestamps.push(e.logLine.timestamp);
    if (!id || !BREAK_RACIAL_SPELL_IDS.has(id)) continue;
    const idx = bindBreakToWindow(e.logLine.timestamp);
    // The trinket wins the label when both were pressed on the same CC: the
    // trinket ledger's whole subject is the trinket.
    if (idx >= 0 && !trinketBrokenWindowIdx.has(idx))
      racialBrokenWindow.set(idx, racialName(id) ?? id);
  }

  // Defensive: the remaining-time scan assumes ascending order, and
  // spellCastEvents' ordering is not part of ICombatUnit's contract.
  racialLockTimestamps.sort((a, b) => a - b);

  const ccInstancesUnsorted: Omit<ICCInstance, "drInfo">[] =
    filteredCCWindows.map((w, idx) => {
      const damageTakenDuring = player.damageIn
        .filter(
          (d) =>
            enemyIds.has(d.srcUnitId) &&
            d.logLine.timestamp >= w.applyMs &&
            d.logLine.timestamp <= w.removeMs,
        )
        .reduce((sum, d) => sum + Math.abs(d.effectiveAmount), 0);

      let trinketState: ICCInstance["trinketState"];
      let trinketCDSecondsLeft: number | undefined;
      const breakRacialName = racialBrokenWindow.get(idx);
      if (trinketBrokenWindowIdx.has(idx)) {
        trinketState = "used";
      } else if (breakRacialName) {
        // Checked before the Relentless branch: a racial break is a fact about
        // this CC, while "passive_trinket" only describes the equipped trinket.
        trinketState = "racial_break";
      } else if (trinketType === "Relentless") {
        trinketState = "passive_trinket";
      } else {
        const remainingMs = trinketCooldownRemainingMs(
          trinketCastTimestamps,
          trinketCooldownMs,
          racialLockTimestamps,
          w.applyMs,
        );
        if (remainingMs <= 0) {
          trinketState = "available_unused";
        } else {
          trinketState = "on_cooldown";
          trinketCDSecondsLeft = Math.ceil(remainingMs / 1000);
        }
      }

      // LoS + distance at CC application time. Gap-aware: null when either unit
      // lacks a recent snapshot; suppressed entirely beyond plausible CC range.
      const casterUnit = enemyUnitMap.get(w.srcUnitId);
      const casterPos = casterUnit
        ? getUnitPositionAtTime(casterUnit, w.applyMs, CC_POSITION_MAX_GAP_MS)
        : null;
      const targetPos = getUnitPositionAtTime(
        player,
        w.applyMs,
        CC_POSITION_MAX_GAP_MS,
      );

      const rawDistance =
        casterPos && targetPos ? distanceBetween(casterPos, targetPos) : null;
      const distanceYards =
        rawDistance !== null && rawDistance <= CC_MAX_PLAUSIBLE_RANGE_YARDS
          ? Math.round(rawDistance * 10) / 10
          : null;

      const losBlocked =
        distanceYards !== null && casterPos && targetPos
          ? (() => {
              const los = hasLineOfSight(zoneId, casterPos, targetPos);
              return los === null ? null : !los;
            })()
          : null;

      return {
        atSeconds: (w.applyMs - matchStartMs) / 1000,
        durationSeconds: (w.removeMs - w.applyMs) / 1000,
        spellId: w.spellId,
        spellName: w.spellName,
        sourceName: w.srcName,
        sourceSpec: enemySpecMap.get(w.srcUnitId) ?? "Unknown",
        damageTakenDuring,
        trinketState,
        trinketCDSecondsLeft,
        ...(breakRacialName ? { breakRacialName } : {}),
        distanceYards,
        losBlocked,
      };
    });

  const sorted = [...ccInstancesUnsorted].sort(
    (a, b) => a.atSeconds - b.atSeconds,
  );
  const drAnnotations = computeIncomingDR(sorted, matchStartMs);
  const ccInstances: ICCInstance[] = sorted.map((cc, i) => ({
    ...cc,
    drInfo: drAnnotations[i] ?? null,
  }));

  const missedTrinketWindows = ccInstances.filter(
    (c) =>
      c.trinketState === "available_unused" &&
      c.damageTakenDuring >= SIGNIFICANT_CC_DAMAGE,
  );

  const rootInstances: IRootInstance[] = rootWindows
    .map((w) => ({
      atSeconds: (w.applyMs - matchStartMs) / 1000,
      durationSeconds: (w.removeMs - w.applyMs) / 1000,
      spellId: w.spellId,
      spellName: w.spellName,
      sourceName: w.srcName,
      sourceSpec: enemySpecMap.get(w.srcId) ?? "Unknown",
    }))
    .sort((a, b) => a.atSeconds - b.atSeconds);

  const disarmInstances: IRootInstance[] = disarmWindows
    .map((w) => ({
      atSeconds: (w.applyMs - matchStartMs) / 1000,
      durationSeconds: (w.removeMs - w.applyMs) / 1000,
      spellId: w.spellId,
      spellName: w.spellName,
      sourceName: w.srcName,
      sourceSpec: enemySpecMap.get(w.srcId) ?? "Unknown",
    }))
    .sort((a, b) => a.atSeconds - b.atSeconds);

  const interruptInstances: IInterruptInstance[] = [];
  for (const action of player.actionIn) {
    if (action.logLine.event !== LogEvent.SPELL_INTERRUPT) continue;
    if (!enemyIds.has(action.srcUnitId)) continue;
    const extraAction = action as unknown as CombatExtraSpellAction;
    // Raw SPELL_INTERRUPT semantics: spellId = the interrupt (kick),
    // extraSpellId = the spell that was interrupted (matchTimeline's [KICK]
    // lines have always rendered it this way). The ported version had them
    // swapped, following an assumption about the old parser, which also made the
    // lockout duration look up the wrong table — case 13 of a gate predicate
    // forking, surfaced by the ledger-vs-timeline contradiction in the
    // 2026-07-16 DPS baseline.
    const kickSpellId = action.spellId ?? "";
    // Single-source predicate for kick lockout duration (kickLockoutSeconds):
    // dispelAnalysis's "dispeller locked out" gate and this site must use the
    // same table and the same fallback — inlining it on each side is a breeding
    // ground for divergence.
    const lockoutDurationSeconds = kickLockoutSeconds(kickSpellId);
    interruptInstances.push({
      atSeconds: (action.timestamp - matchStartMs) / 1000,
      lockoutDurationSeconds,
      postKick: "idle",
      switchSpellName: null,
      switchDelayS: null,
      switchWasHardCast: null,
      firstActionDelayS: null,
      kickSpellId,
      kickSpellName: getEnglishSpellName(kickSpellId, action.spellName),
      interruptedSpellId: extraAction.extraSpellId ?? "",
      interruptedSpellName: getEnglishSpellName(
        extraAction.extraSpellId ?? "",
        extraAction.extraSpellName,
      ),
      sourceName: action.srcUnitName,
      sourceSpec: enemySpecMap.get(action.srcUnitId) ?? "Unknown",
    });
  }
  interruptInstances.sort((a, b) => a.atSeconds - b.atSeconds);

  // BACKLOG #36(b): classify the post-kick behavior. The window matches the
  // research criterion exactly (5s straddles the 3–4s lockout, so "idle" means
  // the player did nothing even after the lockout ended).
  {
    const castTimes = player.spellCastEvents
      .filter((e) => e.logLine.event === LogEvent.SPELL_CAST_SUCCESS)
      .map((e) => ({
        t: (e.logLine.timestamp - matchStartMs) / 1000,
        spellId: e.spellId ?? "",
        spellName: getEnglishSpellName(e.spellId ?? "", e.spellName),
      }))
      .sort((a, b) => a.t - b.t);
    // Optional field: absent on old archives. Absence is "unknown", never
    // "instant" — see IInterruptInstance.switchWasHardCast.
    const rawCastStarts = player.castStartEvents;
    const haveCastStarts =
      Array.isArray(rawCastStarts) && rawCastStarts.length > 0;
    const castStarts = (rawCastStarts ?? []).map((e) => ({
      t: (e.logLine.timestamp - matchStartMs) / 1000,
      spellId: e.spellId ?? "",
    }));
    for (const inst of interruptInstances) {
      const after = castTimes.filter(
        (c) =>
          c.t > inst.atSeconds && c.t <= inst.atSeconds + POST_KICK_WINDOW_S,
      );
      if (after.length === 0) {
        inst.postKick = "idle";
        inst.firstActionDelayS = null;
        continue;
      }
      inst.firstActionDelayS = after[0]!.t - inst.atSeconds;
      const lockedMask = spellSchoolMask(inst.interruptedSpellId);
      // `find` where this used to read `some`: identical predicate (some(p)
      // is true iff find(p) is defined), but it also NAMES the cast so the
      // rendered line can cite the one it is actually talking about.
      const switchCast =
        lockedMask === undefined
          ? undefined
          : after.find((c) => {
              const m = spellSchoolMask(c.spellId);
              return m !== undefined && (m & lockedMask) === 0;
            });
      inst.postKick = switchCast !== undefined ? "switched" : "acted";
      if (switchCast !== undefined) {
        inst.switchSpellName = switchCast.spellName;
        inst.switchDelayS = switchCast.t - inst.atSeconds;
        inst.switchWasHardCast = haveCastStarts
          ? castStarts.some(
              (st) =>
                st.spellId === switchCast.spellId &&
                st.t <= switchCast.t &&
                st.t >= switchCast.t - CAST_START_LOOKBACK_S,
            )
          : null;
      }
    }
  }

  // ─── CC Avoidance Correlation Logic ───────────────────────────────────────
  const ccAvoidedInstances: ICCAvoidedInstance[] = [];

  // Track active buff intervals on the player
  const activeBuffs: Array<{
    spellId: string;
    name: string;
    applyMs: number;
    removeMs: number;
  }> = [];
  const pendingBuffs = new Map<string, { applyMs: number; name: string }>();

  if (player.info?.interestingAurasJSON) {
    try {
      const initialAuras = JSON.parse(player.info.interestingAurasJSON);
      if (Array.isArray(initialAuras)) {
        for (const auraId of initialAuras) {
          const spellIdStr = String(auraId);
          if (CC_AVOIDANCE_BUFF_SPELLS.has(spellIdStr)) {
            pendingBuffs.set(spellIdStr, {
              applyMs: combat.startTime,
              name: CC_AVOIDANCE_BUFF_SPELLS.get(spellIdStr) ?? "",
            });
          } else if (DRUID_FORM_BUFFS.has(spellIdStr)) {
            pendingBuffs.set(spellIdStr, {
              applyMs: combat.startTime,
              name: DRUID_FORM_BUFFS.get(spellIdStr) ?? "",
            });
          }
        }
      }
    } catch {
      // Ignore parse errors
    }
  }

  for (const aura of player.auraEvents) {
    const spellId = aura.spellId;
    if (
      !spellId ||
      (!CC_AVOIDANCE_BUFF_SPELLS.has(spellId) && !DRUID_FORM_BUFFS.has(spellId))
    )
      continue;

    const event = aura.logLine.event;
    if (
      event === LogEvent.SPELL_AURA_APPLIED ||
      event === LogEvent.SPELL_AURA_REFRESH
    ) {
      const pending = pendingBuffs.get(spellId);
      if (pending) {
        activeBuffs.push({
          spellId,
          name: pending.name,
          applyMs: pending.applyMs,
          removeMs: aura.timestamp,
        });
      }
      pendingBuffs.set(spellId, {
        applyMs: aura.timestamp,
        name:
          CC_AVOIDANCE_BUFF_SPELLS.get(spellId) ??
          DRUID_FORM_BUFFS.get(spellId) ??
          "",
      });
    } else if (event === LogEvent.SPELL_AURA_REMOVED) {
      const pending = pendingBuffs.get(spellId);
      if (pending) {
        activeBuffs.push({
          spellId,
          name: pending.name,
          applyMs: pending.applyMs,
          removeMs: aura.timestamp,
        });
        pendingBuffs.delete(spellId);
      }
    }
  }

  for (const [spellId, pending] of pendingBuffs.entries()) {
    activeBuffs.push({
      spellId,
      name: pending.name,
      applyMs: pending.applyMs,
      removeMs: combat.endTime,
    });
  }

  // 1. Unified Buff & Mobility CC Avoidance (targeted and ground CCs)
  for (const enemy of enemies) {
    // F134: include the enemy's pet/guardian casts so a whiffed pet CC (Water Elemental Freeze,
    // Felhunter Spell Lock, Succubus Seduction, Hunter-pet Intimidation) is credited as an avoidance.
    // Landed CC is already counted aura-side in ccInstances, so this only affects the avoided numerator.
    for (const cast of [
      ...enemy.spellCastEvents,
      ...(enemy.petSpellCastEvents ?? []),
    ]) {
      if (cast.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
      if (
        !cast.spellId ||
        (!ccSpellIds.has(cast.spellId) &&
          !GROUND_CC_SPELL_IDS.has(cast.spellId))
      )
        continue;

      const isTargeted =
        cast.destUnitId === player.id || cast.destUnitName === player.name;
      const isGroundCC = GROUND_CC_SPELL_IDS.has(cast.spellId);

      if (isTargeted || isGroundCC) {
        const castTimeMs = cast.logLine.timestamp;
        const gotCCd = ccInstances.some(
          (cc) =>
            Math.abs(cc.atSeconds * 1000 - (castTimeMs - matchStartMs)) <=
              1500 && cc.spellId === cast.spellId,
        );

        if (!gotCCd) {
          const ccSpellName = getEnglishSpellName(cast.spellId, cast.spellName);
          // Single-source predicate (2026-08-07, shared-predicate rule / CC
          // avoidance gating IS the spec): school gate (magic-only immunity
          // cannot explain a physical CC), Druid-form gate (forms only credited
          // for Polymorph/Hex, never another targeted CC or a ground CC — H14),
          // and the ground-vs-targeted mobility gate all live in
          // applicableCCAvoidanceIds; this sweep only asks membership, it does
          // not re-derive any of the three gates itself.
          const applicableIds = applicableCCAvoidanceIds(
            cast.spellId,
            ccSpellName,
          );

          // A. Buff-Based Avoidance
          const activeBuff = activeBuffs.find(
            (b) => castTimeMs >= b.applyMs && castTimeMs <= b.removeMs,
          );
          if (activeBuff && applicableIds.has(activeBuff.spellId)) {
            ccAvoidedInstances.push({
              atSeconds: (castTimeMs - matchStartMs) / 1000,
              spellId: cast.spellId,
              spellName: ccSpellName,
              avoidanceSpellName: activeBuff.name,
              avoidanceSpellId: activeBuff.spellId,
              sourceName: enemy.name,
              sourceSpec: enemySpecMap.get(enemy.id) ?? "Unknown",
            });
            continue; // Avoid double counting
          }

          // B. Mobility-Based Avoidance
          const mobilityCast = player.spellCastEvents.find(
            (e) =>
              e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
              e.spellId &&
              REPOSITIONING_SPELL_IDS.has(e.spellId) &&
              Math.abs(e.logLine.timestamp - castTimeMs) <= 1500,
          );
          if (
            mobilityCast &&
            mobilityCast.spellId &&
            applicableIds.has(mobilityCast.spellId)
          ) {
            ccAvoidedInstances.push({
              atSeconds: (castTimeMs - matchStartMs) / 1000,
              spellId: cast.spellId,
              spellName: ccSpellName,
              avoidanceSpellName:
                REPOSITIONING_SPELL_IDS.get(mobilityCast.spellId) ?? "",
              avoidanceSpellId: mobilityCast.spellId,
              sourceName: enemy.name,
              sourceSpec: enemySpecMap.get(enemy.id) ?? "Unknown",
            });
          }
        }
      }
    }
  }

  // 2. Grounding Totem Redirects (only tracked on Shaman players to avoid multi-teammate duplication)
  if (player.class === CombatUnitClass.Shaman) {
    const groundingRedirects: ICCAvoidedInstance[] = [];
    for (const enemy of enemies) {
      for (const cast of enemy.spellCastEvents) {
        if (cast.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
        if (!cast.spellId || !ccSpellIds.has(cast.spellId)) continue;

        const isGroundingTotem =
          cast.destUnitName?.toLowerCase().includes("grounding totem") ||
          (cast.destUnitId?.startsWith("Creature-") &&
            cast.destUnitId.split("-")[5] === "5925");
        if (isGroundingTotem) {
          const castTimeMs = cast.logLine.timestamp;
          groundingRedirects.push({
            atSeconds: (castTimeMs - matchStartMs) / 1000,
            spellId: cast.spellId,
            spellName: getEnglishSpellName(cast.spellId, cast.spellName),
            avoidanceSpellName: "Grounding Totem",
            avoidanceSpellId: GROUNDING_TOTEM_SPELL_ID,
            sourceName: enemy.name,
            sourceSpec: enemySpecMap.get(enemy.id) ?? "Unknown",
          });
        }
      }
    }
    // Grounding redirects only the FIRST targeted spell per placement — collapse credits that fall
    // within one placement window so a single totem is not credited for multiple CCs.
    groundingRedirects.sort((a, b) => a.atSeconds - b.atSeconds);
    let lastKeptSeconds = -Infinity;
    for (const g of groundingRedirects) {
      if (g.atSeconds - lastKeptSeconds > GROUNDING_DEDUPE_SECONDS) {
        ccAvoidedInstances.push(g);
        lastKeptSeconds = g.atSeconds;
      }
    }
  }

  // 4. Paladin Blessing of Sacrifice Breaks
  if (player.class === CombatUnitClass.Paladin) {
    for (const cc of ccInstances) {
      const ccAppliedTimeMs = cc.atSeconds * 1000 + matchStartMs;
      if (BREAKABLE_CC_SPELL_IDS.has(cc.spellId) && cc.durationSeconds <= 4.0) {
        const sacrificeCast = player.spellCastEvents.find(
          (e) =>
            (e.spellId === "6940" || e.spellId === "199448") &&
            e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
            ccAppliedTimeMs >= e.logLine.timestamp &&
            ccAppliedTimeMs - e.logLine.timestamp <= 12000,
        );
        if (sacrificeCast) {
          ccAvoidedInstances.push({
            atSeconds: cc.atSeconds,
            spellId: cc.spellId,
            spellName: cc.spellName,
            avoidanceSpellName: "Blessing of Sacrifice",
            avoidanceSpellId: sacrificeCast.spellId || "6940",
            sourceName: cc.sourceName,
            sourceSpec: cc.sourceSpec,
          });
        }
      }
    }
  }

  // 5. Shadow Word: Death Breaks (only Priest players)
  if (player.class === CombatUnitClass.Priest) {
    for (const cc of ccInstances) {
      const ccAppliedTimeMs = cc.atSeconds * 1000 + matchStartMs;
      if (BREAKABLE_CC_SPELL_IDS.has(cc.spellId) && cc.durationSeconds <= 1.0) {
        const swdCast = player.spellCastEvents.find(
          (e) =>
            e.spellId === SHADOW_WORD_DEATH_SPELL_ID &&
            e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
            e.logLine.timestamp >= ccAppliedTimeMs - 500 &&
            e.logLine.timestamp <= ccAppliedTimeMs,
        );
        if (swdCast) {
          ccAvoidedInstances.push({
            atSeconds: cc.atSeconds,
            spellId: cc.spellId,
            spellName: cc.spellName,
            avoidanceSpellName: "Shadow Word: Death",
            avoidanceSpellId: SHADOW_WORD_DEATH_SPELL_ID,
            sourceName: cc.sourceName,
            sourceSpec: cc.sourceSpec,
          });
        }
      }
    }
  }

  // 6. Tremor Totem Breaks (only Shaman players)
  if (player.class === CombatUnitClass.Shaman) {
    for (const cc of ccInstances) {
      const ccAppliedTimeMs = cc.atSeconds * 1000 + matchStartMs;
      if (
        TREMOR_BREAKABLE_CC_IDS.has(cc.spellId) &&
        cc.durationSeconds <= 2.0
      ) {
        const tremorCast = player.spellCastEvents.find(
          (e) =>
            e.spellId === "8143" &&
            e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
            ccAppliedTimeMs >= e.logLine.timestamp &&
            ccAppliedTimeMs - e.logLine.timestamp <= 10000,
        );
        if (tremorCast) {
          ccAvoidedInstances.push({
            atSeconds: cc.atSeconds,
            spellId: cc.spellId,
            spellName: cc.spellName,
            avoidanceSpellName: "Tremor Totem",
            avoidanceSpellId: "8143",
            sourceName: cc.sourceName,
            sourceSpec: cc.sourceSpec,
          });
        }
      }
    }
  }

  ccAvoidedInstances.sort((a, b) => a.atSeconds - b.atSeconds);

  return {
    playerName: player.name,
    playerSpec: specToString(player.spec),
    trinketType,
    trinketCooldownSeconds,
    ccInstances,
    trinketUseTimes: trinketCastTimestamps.map(
      (ts) => (ts - matchStartMs) / 1000,
    ),
    missedTrinketWindows,
    rootInstances,
    disarmInstances,
    interruptInstances,
    ccAvoidedInstances,
  };
}

// ---------------------------------------------------------------------------
// Formatter
// ---------------------------------------------------------------------------

export function formatCCTrinketForContext(
  summaries: IPlayerCCTrinketSummary[],
): string[] {
  const lines: string[] = [];
  lines.push("CC RECEIVED BY YOUR TEAM (enemies CCing you) + TRINKET USAGE:");

  const hasCCData = summaries.some((s) => s.ccInstances.length > 0);
  if (!hasCCData) {
    lines.push("  No hard CC events detected on your team.");
    return lines;
  }

  for (const s of summaries) {
    if (s.ccInstances.length === 0) continue;

    // Aggregate CC counts by type
    const countBySpell = new Map<string, number>();
    let immuneOrReducedCount = 0;
    let meleeCCCount = 0;
    const missedTrinketCount = s.missedTrinketWindows.length;

    for (const cc of s.ccInstances) {
      countBySpell.set(cc.spellName, (countBySpell.get(cc.spellName) ?? 0) + 1);
      if (cc.drInfo && cc.drInfo.level !== "Full") immuneOrReducedCount++;
      if (
        cc.distanceYards !== null &&
        cc.distanceYards <= 8 &&
        cc.losBlocked !== true
      )
        meleeCCCount++;
    }

    const ccBreakdown = [...countBySpell.entries()]
      .sort((a, b) => b[1] - a[1])
      .map(([name, count]) => `${count}× ${name}`)
      .join(", ");
    const trinketCdStr =
      s.trinketType === "Relentless" || s.trinketType === "Unknown"
        ? s.trinketType
        : `${s.trinketType} trinket`;

    const notes: string[] = [];
    if (immuneOrReducedCount > 0)
      notes.push(`${immuneOrReducedCount} reduced/immune DR`);
    if (meleeCCCount > 0) notes.push(`${meleeCCCount} at melee range`);
    if (missedTrinketCount > 0) {
      const totalDmg = s.missedTrinketWindows.reduce(
        (sum, w) => sum + w.damageTakenDuring,
        0,
      );
      notes.push(
        `⚠ ${missedTrinketCount} missed trinket window(s) (${Math.round(totalDmg / 1000)}k dmg total)`,
      );
    }
    const noteStr = notes.length > 0 ? ` [${notes.join("; ")}]` : "";

    // Trinket use times outside CC windows
    const trinketResponseWindowS = TRINKET_RESPONSE_WINDOW_MS / 1000;
    const offCCUses = s.trinketUseTimes.filter(
      (t) =>
        !s.ccInstances.some(
          (cc) => Math.abs(cc.atSeconds - t) <= trinketResponseWindowS,
        ),
    );
    const trinketStr =
      offCCUses.length > 0
        ? `${trinketCdStr} used off-CC at ${offCCUses.map(fmtTime).join(", ")}`
        : trinketCdStr;

    lines.push(
      `  ${s.playerSpec} (${s.playerName}): ${s.ccInstances.length} CC — ${ccBreakdown} | ${trinketStr}${noteStr}`,
    );

    // Per-window detail for missed trinket windows — the highest-value CC instances.
    // Position annotation (distance / LoS at application) only when advanced logging supplied it.
    for (const w of s.missedTrinketWindows) {
      const posStr =
        w.distanceYards !== null
          ? ` — ${w.distanceYards}yd from caster${w.losBlocked === true ? ", LoS blocked" : ""}`
          : "";
      lines.push(
        `    ⚠ Missed trinket: ${fmtTime(w.atSeconds)} ${w.spellName} (${Math.round(w.durationSeconds)}s, ${Math.round(w.damageTakenDuring / 1000)}k dmg)${posStr}`,
      );
    }
  }

  return lines;
}
