import { ICombatUnit, LogEvent } from "@gladlog/parser-compat";

import kitRaw from "../data/interruptKitGenerated.json";
import { spellEffectData } from "../data/spellEffectData";
import { specToString } from "./cooldowns";

/**
 * Which interrupt a combatant HAS — from official data, per player (GH #78,
 * user correction 2026-09-12: "奶龙和奶骑是没有打断的 … 能不能从官方的数据弄清楚").
 *
 * Until 2026-09-12 this was a hand table that gave every Paladin Rebuke and
 * every Evoker Quell ("class-wide except Hunter / Priest / Monk"); it was
 * true expansions ago and had been wrong long enough that the kick-priority
 * examples rendered a Holy Paladin's "Rebuke, never pressed all game". The
 * table it reads now is generated by scripts/datagen/genInterruptKit.ts:
 *   classBaseline  DB2 SkillLineAbility.ClassMask   (Pummel, Kick, Counterspell, Disrupt)
 *   specBaseline   DB2 SpecializationSpells         (Silence → Shadow)
 *   talent         the spec's talent tree (DB2 trait tables via Raidbots):
 *                  Rebuke → Protection/Retribution only, Quell → Devastation/
 *                  Augmentation only, Skull Bash → Feral/Guardian, Spear Hand
 *                  Strike → Brewmaster/Windwalker, Solar Beam → Balance;
 *                  Wind Shear / Mind Freeze / Counter Shot / Muzzle every spec
 *                  of their class. A talent counts when the player's
 *                  COMBATANT_INFO shows the node taken (id1 = node, id2 = entry);
 *                  when the log carries NO talent list at all (old archives,
 *                  synthetic fixtures) the spec's tree availability is used —
 *                  an explicit degradation, never an assumption about a
 *                  player whose talents we can see.
 *   pet            Spell Lock / Axe Toss live on the pet's skill line; they
 *                  count only when that pet cast one (observed, never assumed).
 * Corpus cross-check (704 archive files, 2026-09-12): every spec this table
 * gives no interrupt cast none in 100 % of rounds; every spec it gives one
 * cast it in 57–98 % of rounds.
 */
interface InterruptDef {
  spellId: string;
  name: string;
}
interface KitEntry {
  name: string;
  classBaseline: number[];
  specBaseline: number[];
  talent: Record<string, { nodeId: number; entryId: number }>;
  pet: boolean;
}
const KIT = (kitRaw as unknown as { interrupts: Record<string, KitEntry> })
  .interrupts;
/** Every interrupt id the kit can assign — the id universe genSpellReach.ts
 * resolves official cast ranges for. */
export const INTERRUPT_SPELL_IDS: readonly string[] = Object.keys(KIT);

/** The interrupt this unit has, or null (Holy Paladin, Preservation Evoker,
 * Restoration Druid, Mistweaver, Disc/Holy Priest, a Retribution Paladin who
 * did not take Rebuke …). Baseline before talent, talent before pet. */
export function interruptForUnit(unit: ICombatUnit): InterruptDef | null {
  const classId = Number(unit.class);
  const specId = String(unit.spec);
  const talents = unit.info?.talents;
  const hasTalentData = Array.isArray(talents) && talents.length > 0;
  let pet: InterruptDef | null = null;
  let talentPick: InterruptDef | null = null;
  for (const [spellId, e] of Object.entries(KIT)) {
    const def = { spellId, name: e.name };
    if (e.classBaseline.includes(classId) || e.specBaseline.includes(Number(specId)))
      return def;
    const node = e.talent[specId];
    if (node && !talentPick) {
      const taken = hasTalentData
        ? talents.some((t) => t.id1 === node.nodeId && t.id2 === node.entryId)
        : true; // no talent list in the log → tree availability
      if (taken) talentPick = def;
    }
    if (e.pet && !pet) {
      const observed = (unit.petSpellCastEvents ?? []).some(
        (c) => c.spellId === spellId && c.logLine.event === LogEvent.SPELL_CAST_SUCCESS,
      );
      if (observed) pet = def;
    }
  }
  return talentPick ?? pet;
}

export interface IEnemyInterruptState {
  enemyName: string;
  spec: string;
  spellName: string;
  /** Seconds until the interrupt is available again; 0 = ready now. */
  cdRemainingSeconds: number;
}

/**
 * B128: for each enemy that has an interrupt, its ready/on-cooldown state at atMs. An interrupt is on
 * cooldown when the enemy cast it within its cooldown window; otherwise it is ready (including when it
 * was never cast). This lets the timeline show whether an owner channel could have been kicked.
 */
export function computeEnemyInterruptAvailability(
  enemies: ICombatUnit[],
  atMs: number,
): IEnemyInterruptState[] {
  const result: IEnemyInterruptState[] = [];
  for (const enemy of enemies) {
    const def = interruptForUnit(enemy);
    if (!def) continue;
    const cooldownSeconds = spellEffectData[def.spellId]?.cooldownSeconds ?? 15;

    // Most recent successful cast of this interrupt at or before atMs.
    let lastCastMs = -Infinity;
    const allCasts = [
      ...enemy.spellCastEvents,
      ...(enemy.petSpellCastEvents ?? []),
    ];
    for (const e of allCasts) {
      if (e.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
      if (e.spellId !== def.spellId) continue;
      const ts = e.logLine.timestamp;
      if (ts <= atMs && ts > lastCastMs) lastCastMs = ts;
    }

    const cdRemainingSeconds =
      lastCastMs === -Infinity
        ? 0
        : Math.max(0, Math.round(cooldownSeconds - (atMs - lastCastMs) / 1000));
    result.push({
      enemyName: enemy.name,
      spec: specToString(enemy.spec),
      spellName: def.name,
      cdRemainingSeconds,
    });
  }
  return result;
}
