import { ICombatUnit, LogEvent } from "@gladlog/parser-compat";

import kitRaw from "../data/interruptKitGenerated.json";
import { spellEffectData } from "../data/spellEffectData";
import { specToString } from "./cooldowns";

/**
 * Which interrupt a combatant HAS — from official data, per player (GH #78,
 * user correction 2026-09-12: "奶龙和奶骑是没有打断的 … 能不能从官方的数据弄清楚").
 *
 * Until 2026-09-12 this was a hand table that gave every Paladin Rebuke and
 * every Evoker Quell ("class-wide except Hunter / Priest / Monk"); it was
 * true expansions ago and had been wrong long enough that the kick-priority
 * examples rendered a Holy Paladin's "Rebuke, never pressed all game". The
 * table it reads now is generated by scripts/datagen/genInterruptKit.ts:
 *   classBaseline  DB2 SkillLineAbility.ClassMask   (Pummel, Kick, Counterspell, Disrupt)
 *   specBaseline   DB2 SpecializationSpells         (Silence → Shadow)
 *   talent         the spec's talent tree (DB2 trait tables via Raidbots):
 *                  Rebuke → Protection/Retribution only, Quell → Devastation/
 *                  Augmentation only, Skull Bash → Feral/Guardian, Spear Hand
 *                  Strike → Brewmaster/Windwalker, Solar Beam → Balance;
 *                  Wind Shear / Mind Freeze / Counter Shot / Muzzle every spec
 *                  of their class. A talent counts when the player's
 *                  COMBATANT_INFO shows the node taken (id1 = node, id2 = entry);
 *                  when the log carries NO talent list at all (old archives,
 *                  synthetic fixtures) the spec's tree availability is used —
 *                  an explicit degradation, never an assumption about a
 *                  player whose talents we can see.
 *   pet            Spell Lock / Axe Toss live on the pet's skill line; they
 *                  count only when that pet cast one (observed, never assumed).
 * Corpus cross-check (704 archive files, 2026-09-12): every spec this table
 * gives no interrupt cast none in 100 % of rounds; every spec it gives one
 * cast it in 57–98 % of rounds.
 */
interface InterruptDef {
  spellId: string;
  name: string;
  /** Provenance of the possession claim: `true` = class/spec baseline, or a
   * talent node the player's COMBATANT_INFO shows taken; `false` = a
   * tree-availability fallback (no talent list in the log) or a pet ability
   * (observed, but its position is not the owner's). Feasibility gates that
   * need certainty (kick-priority) treat unconfirmed kits as
   * observed-or-nothing. */
  confirmed: boolean;
}
interface KitEntry {
  name: string;
  classBaseline: number[];
  specBaseline: number[];
  talent: Record<string, { nodeId: number; entryId: number }>;
  pet: boolean;
}
const KIT = (kitRaw as unknown as { interrupts: Record<string, KitEntry> })
  .interrupts;
/** Every interrupt id the kit can assign — the id universe genSpellReach.ts
 * resolves official cast ranges for. */
export const INTERRUPT_SPELL_IDS: readonly string[] = Object.keys(KIT);

const castable = (e: KitEntry): boolean =>
  e.classBaseline.length > 0 ||
  e.specBaseline.length > 0 ||
  Object.keys(e.talent).length > 0 ||
  e.pet;

/**
 * The CAST id behind a kick event's spell id. SPELL_INTERRUPT carries the
 * interrupt EFFECT id for some kits (Skull Bash 93985 → 106839, Solar Beam
 * 97547 → 78675, Spell Lock 119910 / 132409 → 19647); those rows sit in the
 * kit with no baseline, talent or pet source, and their SpellMisc range is
 * DB2's 100 yd vision-range placeholder. An effect-only entry resolves to the
 * one same-named castable entry; anything else (a castable id, an effect-only
 * id with no castable twin, an id outside the kit) is returned unchanged.
 * Pure data, no unit: the kicker demonstrably kicked, so its talent reading
 * must not decide which row names the spell (agy review). `kickersInRange`
 * reads castable kit ids (`interruptForUnit`), so kick-eaten's `kickRangeYd`
 * keyed on this resolver measures the same spell.
 */
export function kickCastSpellId(eventSpellId: string): string {
  const e = KIT[eventSpellId];
  if (!e || castable(e)) return eventSpellId;
  const twins = Object.entries(KIT).filter(
    ([id, k]) => id !== eventSpellId && k.name === e.name && castable(k),
  );
  return twins.length === 1 ? twins[0]![0] : eventSpellId;
}

/** Exact ms of cooldown left on `spellId` for this unit at `atMs` (0 = ready),
 * from its most recent successful cast (own or pet) and the official
 * cooldown. The one predicate behind both the timeline's whole-second display
 * and kick-priority's feasibility. */
/** An interrupt's cooldown from the official table, or undefined when the
 * table has no row — shared by the availability ledger below (which falls
 * back to 15 s) and the timeline's `[KICK] … back M:SS` suffix (which renders
 * nothing rather than a guess). GH #103 A3. */
export function interruptCooldownSeconds(spellId: string): number | undefined {
  return spellEffectData[spellId]?.cooldownSeconds;
}

export function interruptCooldownRemainingMs(
  unit: ICombatUnit,
  spellId: string,
  atMs: number,
): number {
  const cooldownSeconds = interruptCooldownSeconds(spellId) ?? 15;
  let lastCastMs = -Infinity;
  for (const e of [
    ...unit.spellCastEvents,
    ...(unit.petSpellCastEvents ?? []),
  ]) {
    if (e.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
    if (e.spellId !== spellId) continue;
    const ts = e.logLine.timestamp;
    if (ts <= atMs && ts > lastCastMs) lastCastMs = ts;
  }
  return lastCastMs === -Infinity
    ? 0
    : Math.max(0, cooldownSeconds * 1000 - (atMs - lastCastMs));
}

/** The interrupt this unit has, or null (Holy Paladin, Preservation Evoker,
 * Restoration Druid, Mistweaver, Disc/Holy Priest, a Retribution Paladin who
 * did not take Rebuke …). Baseline before talent, talent before pet. */
export function interruptForUnit(unit: ICombatUnit): InterruptDef | null {
  const classId = Number(unit.class);
  const specId = String(unit.spec);
  const talents = unit.info?.talents;
  const hasTalentData = Array.isArray(talents) && talents.length > 0;
  let pet: InterruptDef | null = null;
  let talentPick: InterruptDef | null = null;
  for (const [spellId, e] of Object.entries(KIT)) {
    if (
      e.classBaseline.includes(classId) ||
      e.specBaseline.includes(Number(specId))
    )
      return { spellId, name: e.name, confirmed: true };
    const node = e.talent[specId];
    if (node && !talentPick) {
      const taken = hasTalentData
        ? talents.some((t) => t.id1 === node.nodeId && t.id2 === node.entryId)
        : true; // no talent list in the log → tree availability (unconfirmed)
      if (taken)
        talentPick = { spellId, name: e.name, confirmed: hasTalentData };
    }
    if (e.pet && !pet) {
      const observed = (unit.petSpellCastEvents ?? []).some(
        (c) =>
          c.spellId === spellId &&
          c.logLine.event === LogEvent.SPELL_CAST_SUCCESS,
      );
      if (observed) pet = { spellId, name: e.name, confirmed: false };
    }
  }
  return talentPick ?? pet;
}

export interface IEnemyInterruptState {
  enemyName: string;
  spec: string;
  spellName: string;
  /** Seconds until the interrupt is available again; 0 = ready now. */
  cdRemainingSeconds: number;
  /** Whether the enemy has been observed casting this interrupt at or before atMs (GH #88, B8). */
  seen: boolean;
  /** Whether this interrupt is assumed ready (ready on cooldown, but never yet observed cast in this match at or before atMs). */
  assumedReady: boolean;
}

/**
 * B128 / GH #88 (B8): for each enemy that has an interrupt, its ready/on-cooldown/assumed-ready state at atMs.
 * An interrupt is on cooldown when the enemy cast it within its cooldown window; otherwise it is ready.
 * If it has never yet been cast at or before atMs, it is marked as `assumedReady: true` and `seen: false`,
 * preventing consumers from falsely accusing the player of hardcasting in range when the enemy never kicks.
 */
export function computeEnemyInterruptAvailability(
  enemies: ICombatUnit[],
  atMs: number,
): IEnemyInterruptState[] {
  const result: IEnemyInterruptState[] = [];
  for (const enemy of enemies) {
    const def = interruptForUnit(enemy);
    if (!def) continue;
    // whole-second for the timeline's display; the exact value lives in
    // interruptCooldownRemainingMs (kick-priority reads that one — 0.4 s left
    // is NOT ready)
    const cdRemainingSeconds = Math.round(
      interruptCooldownRemainingMs(enemy, def.spellId, atMs) / 1000,
    );
    const seen = [
      ...(enemy.spellCastEvents ?? []),
      ...(enemy.petSpellCastEvents ?? []),
    ].some(
      (e) =>
        e.spellId === def.spellId &&
        e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
        e.logLine.timestamp <= atMs,
    );
    result.push({
      enemyName: enemy.name,
      spec: specToString(enemy.spec),
      spellName: def.name,
      cdRemainingSeconds,
      seen,
      assumedReady: cdRemainingSeconds === 0 && !seen,
    });
  }
  return result;
}
