import { ICombatUnit, LogEvent } from "@gladlog/parser-compat";

import kitRaw from "../data/interruptKitGenerated.json";
import { spellEffectData } from "../data/spellEffectData";
import {
  eventReductionsFor,
  onInterruptReductionFor,
} from "../data/talentScriptedCooldowns";
import { castBlockingAuraAt, enemySourceIds } from "./cannotCastIntervals";
import {
  chargeStateAt,
  playerTalentIdSets,
  specToString,
  unitCooldownOf,
} from "./cooldowns";
import { isDeadAt } from "./unitDeath";

/**
 * Which interrupt a combatant HAS — from official data, per player (GH #78,
 * user correction 2026-09-12: "奶龙和奶骑是没有打断的 … 能不能从官方的数据弄清楚").
 *
 * Until 2026-09-12 this was a hand table that gave every Paladin Rebuke and
 * every Evoker Quell ("class-wide except Hunter / Priest / Monk"); it was
 * true expansions ago and had been wrong long enough that the kick-priority
 * examples rendered a Holy Paladin's "Rebuke, never pressed all game". The
 * table it reads now is generated by scripts/datagen/genInterruptKit.ts:
 *   classBaseline  DB2 SkillLineAbility.ClassMask   (Pummel, Kick, Counterspell, Disrupt)
 *   specBaseline   DB2 SpecializationSpells         (Silence → Shadow)
 *   talent         the spec's talent tree (DB2 trait tables via Raidbots):
 *                  Rebuke → Protection/Retribution only, Quell → Devastation/
 *                  Augmentation only, Skull Bash → Feral/Guardian, Spear Hand
 *                  Strike → Brewmaster/Windwalker, Solar Beam → Balance;
 *                  Wind Shear / Mind Freeze / Counter Shot / Muzzle every spec
 *                  of their class. A talent counts when the player's
 *                  COMBATANT_INFO shows the node taken (id1 = node, id2 = entry);
 *                  when the log carries NO talent list at all (old archives,
 *                  synthetic fixtures) the spec's tree availability is used —
 *                  an explicit degradation, never an assumption about a
 *                  player whose talents we can see.
 *   pet            Spell Lock / Axe Toss live on the pet's skill line; they
 *                  count only when that pet cast one (observed, never assumed).
 * Corpus cross-check (704 archive files, 2026-09-12): every spec this table
 * gives no interrupt cast none in 100 % of rounds; every spec it gives one
 * cast it in 57–98 % of rounds.
 */
interface InterruptDef {
  spellId: string;
  name: string;
  /** Provenance of the possession claim: `true` = class/spec baseline, or a
   * talent node the player's COMBATANT_INFO shows taken; `false` = a
   * tree-availability fallback (no talent list in the log) or a pet ability
   * (observed, but its position is not the owner's). Feasibility gates that
   * need certainty (kick-priority) treat unconfirmed kits as
   * observed-or-nothing. */
  confirmed: boolean;
}
interface KitEntry {
  name: string;
  classBaseline: number[];
  specBaseline: number[];
  talent: Record<string, { nodeId: number; entryId: number }>;
  pet: boolean;
}
const KIT = (kitRaw as unknown as { interrupts: Record<string, KitEntry> })
  .interrupts;
/** Every interrupt id the kit can assign — the id universe genSpellReach.ts
 * resolves official cast ranges for. */
export const INTERRUPT_SPELL_IDS: readonly string[] = Object.keys(KIT);

const castable = (e: KitEntry): boolean =>
  e.classBaseline.length > 0 ||
  e.specBaseline.length > 0 ||
  Object.keys(e.talent).length > 0 ||
  e.pet;

/**
 * The CAST id behind a kick event's spell id. SPELL_INTERRUPT carries the
 * interrupt EFFECT id for some kits (Skull Bash 93985 → 106839, Solar Beam
 * 97547 → 78675, Spell Lock 119910 / 132409 → 19647); those rows sit in the
 * kit with no baseline, talent or pet source, and their SpellMisc range is
 * DB2's 100 yd vision-range placeholder. An effect-only entry resolves to the
 * one same-named castable entry; anything else (a castable id, an effect-only
 * id with no castable twin, an id outside the kit) is returned unchanged.
 * Pure data, no unit: the kicker demonstrably kicked, so its talent reading
 * must not decide which row names the spell (agy review). `kickersInRange`
 * reads castable kit ids (`interruptForUnit`), so kick-eaten's `kickRangeYd`
 * keyed on this resolver measures the same spell.
 */
export function kickCastSpellId(eventSpellId: string): string {
  const e = KIT[eventSpellId];
  if (!e || castable(e)) return eventSpellId;
  const twins = Object.entries(KIT).filter(
    ([id, k]) => id !== eventSpellId && k.name === e.name && castable(k),
  );
  return twins.length === 1 ? twins[0]![0] : eventSpellId;
}

/** Exact ms of cooldown left on `spellId` for this unit at `atMs` (0 = ready),
 * from its most recent successful cast (own or pet) and the official
 * cooldown. The one predicate behind both the timeline's whole-second display
 * and kick-priority's feasibility. */
/** An interrupt's cooldown, or undefined when the official table has no row
 * — shared by the availability ledger below (which falls back to 15 s) and
 * the timeline's `[KICK] … back M:SS` suffix (which renders nothing rather
 * than a guess). GH #103 A3. With the kicker it is THEIR cooldown
 * (`unitCooldownOf`: talents, PvP talents, spec passives — Restoration
 * Shaman's Wind Shear is 30 s, not 12; Quick Witted, Honed Reflexes …),
 * talent impact audit 2026-09-26; without one, the untalented official row. */
export function interruptCooldownSeconds(
  spellId: string,
  unit?: ICombatUnit,
): number | undefined {
  const base = spellEffectData[spellId]?.cooldownSeconds;
  if (base === undefined) return undefined;
  return (unit && unitCooldownOf(unit, spellId)?.cooldownSeconds) ?? base;
}

/** A landed kick's SPELL_INTERRUPT event pairs with the cast within this
 * window. Also the burst-answered landed test's (sync-burst F-B1). Lives
 * here (kickAudit.ts re-exports it) so the cooldown below and the audit pair
 * a press with its interrupt the same way. */
export const LANDED_PAIR_MS = 1_000;

/**
 * The cooldown of ONE press of an interrupt, in seconds: the unit's
 * talent-resolved cooldown, less what an on-interrupt talent gives back when
 * that press interrupted a cast (`ON_INTERRUPT_COOLDOWN_REDUCTIONS`:
 * Coldthirst, Light of the Sun). "Interrupted" = a SPELL_INTERRUPT sourced by
 * the unit within `LANDED_PAIR_MS` of the press. FT-T11c: the one number
 * behind `[KICK] … back m:ss`, the readiness below (kick-priority, `enemy
 * interrupts UP`) and the owner's [RES] kick entry — 48 `back` times of the
 * 605-file capture were contradicted by the same unit's next kick.
 */
export function interruptPressCooldownSeconds(
  unit: ICombatUnit,
  spellId: string,
  pressMs: number,
  cooldownSeconds: number,
): number {
  // THIS press's interrupt: the SPELL_INTERRUPT carries the kick's own id or
  // its effect id (Solar Beam 97547 → 78675), and it is on the unit the
  // press was aimed at — Light of the Sun pays for the PRIMARY target only,
  // and a caster who walks into a standing Solar Beam is interrupted by a
  // press that did not land on him (codex 40-FT-40). A press whose row
  // names no target accepts any.
  const kickId = kickCastSpellId(spellId);
  // the press's own cast rows (own or pet; one press can log two ids)
  const rows = [
    ...unit.spellCastEvents,
    ...(unit.petSpellCastEvents ?? []),
  ].filter(
    (e) =>
      e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
      kickCastSpellId(e.spellId ?? "") === kickId &&
      Math.abs(e.logLine.timestamp - pressMs) <= PRESS_ROW_PAIR_MS,
  );
  // no press row at that instant: nothing says what it was aimed at — the
  // static cooldown (a cooldown is shortened on evidence only)
  if (rows.length === 0) return cooldownSeconds;
  const aimedAt = rows.find(
    (e) => !!e.destUnitId && e.destUnitId !== NO_UNIT_GUID,
  )?.destUnitId;
  const landed = (unit.actionOut ?? []).some(
    (a) =>
      a.logLine.event === LogEvent.SPELL_INTERRUPT &&
      kickCastSpellId(a.spellId ?? "") === kickId &&
      (aimedAt === undefined || a.destUnitId === aimedAt) &&
      Math.abs(a.logLine.timestamp - pressMs) <= LANDED_PAIR_MS,
  );
  if (!landed) return cooldownSeconds;
  const sets = playerTalentIdSets(unit);
  const back = onInterruptReductionFor(
    kickId,
    (t) => !!sets.talentedSpellIds?.has(t) || sets.pvpTalentIds.has(t),
  );
  return Math.max(0, cooldownSeconds - back);
}
/** Two SPELL_CAST_SUCCESS rows of one press sit this close (Skull Bash logs
 * its cast and effect ids a millisecond apart). */
const PRESS_ROW_PAIR_MS = 50;
const NO_UNIT_GUID = "0000000000000000";

/**
 * When the press behind a SPELL_INTERRUPT comes back, ms. The interrupt can
 * be logged seconds after the press (a caster interrupted by a Solar Beam
 * that has been standing for 4 s): the cooldown runs from the PRESS — the
 * unit's last cast of the kick at or before the interrupt — not from the
 * interrupt line. No cast found (a pet's kick, a cast outside the round) →
 * the interrupt's own time, as before. `[KICK] … back m:ss` reads this, so
 * the line and `interruptCooldownRemainingMs` cannot name different seconds.
 */
export function interruptBackAtMs(
  unit: ICombatUnit,
  eventSpellId: string,
  interruptMs: number,
  cooldownSeconds: number,
): number {
  const castId = kickCastSpellId(eventSpellId);
  // the interrupt line can precede its cast line inside the ms
  const casts = interruptCastsUpTo(
    unit,
    castId,
    interruptMs + PRESS_ROW_PAIR_MS,
  );
  const last = casts.length ? casts[casts.length - 1]! : undefined;
  const backOf = (pressMs: number) =>
    pressMs +
    interruptPressCooldownSeconds(unit, castId, pressMs, cooldownSeconds) *
      1000;
  // a press that had already come back before this interrupt is not the
  // press behind it
  return last !== undefined && backOf(last) > interruptMs
    ? backOf(last)
    : backOf(interruptMs);
}

/** The unit's successful casts of `spellId` (own or pet) up to `atMs`, in
 * time order — the cast list both cooldown readers below work from. */
function interruptCastsUpTo(
  unit: ICombatUnit,
  spellId: string,
  atMs: number,
  strictlyBefore = false,
): number[] {
  const castMs: number[] = [];
  for (const e of [
    ...unit.spellCastEvents,
    ...(unit.petSpellCastEvents ?? []),
  ]) {
    if (e.logLine.event !== LogEvent.SPELL_CAST_SUCCESS) continue;
    if (e.spellId !== spellId) continue;
    if (
      strictlyBefore ? e.logLine.timestamp < atMs : e.logLine.timestamp <= atMs
    )
      castMs.push(e.logLine.timestamp);
  }
  return castMs.sort((a, b) => a - b);
}

/** When a single-charge interrupt cast at `lastCastMs` comes back, as known
 * at `atMs`: last cast + cooldown, minus the event reductions the kicker
 * holds (Storm Conduit: every Lightning Bolt / Chain Lightning −1 s on Wind
 * Shear), only those that happened by `atMs` — the ledger's rule
 * (data/talentScriptedCooldowns). */
function singleChargeReadyMs(
  unit: ICombatUnit,
  spellId: string,
  lastCastMs: number,
  atMs: number,
  cooldownSeconds: number,
): number {
  const sets = playerTalentIdSets(unit);
  const reductions = eventReductionsFor(
    spellId,
    (t) => !!sets.talentedSpellIds?.has(t) || sets.pvpTalentIds.has(t),
  );
  let readyMs =
    lastCastMs +
    interruptPressCooldownSeconds(unit, spellId, lastCastMs, cooldownSeconds) *
      1000;
  if (reductions.length) {
    const events = reductions
      .flatMap((r) =>
        unit.spellCastEvents
          .filter(
            (e) =>
              e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
              r.triggerCastIds.includes(String(e.spellId)) &&
              e.logLine.timestamp > lastCastMs &&
              e.logLine.timestamp <= atMs,
          )
          .map((e) => ({ t: e.logLine.timestamp, ms: r.seconds * 1000 })),
      )
      .sort((a, b) => a.t - b.t);
    for (const e of events) {
      if (e.t >= readyMs) break;
      readyMs = Math.max(e.t, readyMs - e.ms);
    }
  }
  return readyMs;
}

/** Exact ms of cooldown left on `spellId` for this unit at `atMs` (0 = ready),
 * from its successful casts (own or pet) and the unit's talent-resolved
 * cooldown and charge cap. The one predicate behind both the timeline's
 * whole-second display and kick-priority's feasibility. Exact — no rendered-
 * second slack: 0.4 s left is NOT ready. */
export function interruptCooldownRemainingMs(
  unit: ICombatUnit,
  spellId: string,
  atMs: number,
  /** kick-eaten F-K5c: count only kicks logged strictly BEFORE `atMs` ("was
   * the kick in hand when the cast began"); cooldown reductions up to and at
   * `atMs` still apply. Default: kicks at `atMs` are spent. */
  opts?: { kicksBefore?: boolean },
): number {
  const cooldownSeconds = interruptCooldownSeconds(spellId, unit) ?? 15;
  const charges = unitCooldownOf(unit, spellId)?.charges ?? 1;
  const castMs = interruptCastsUpTo(unit, spellId, atMs, opts?.kicksBefore);
  if (!castMs.length) return 0;
  if (charges > 1) {
    // the shared sequential-recharge simulation, in seconds from atMs
    const st = chargeStateAt(
      castMs.map((ms) => (ms - atMs) / 1000),
      cooldownSeconds,
      charges,
      0,
    );
    return st.charges > 0 ? 0 : Math.max(0, st.nextRecharge * 1000);
  }
  const readyMs = singleChargeReadyMs(
    unit,
    spellId,
    castMs[castMs.length - 1]!,
    atMs,
    cooldownSeconds,
  );
  return Math.max(0, readyMs - atMs);
}

/**
 * Since when the interrupt had been ready at `atMs`: the last instant
 * `<= atMs` at which `interruptCooldownRemainingMs` reached 0, or null when
 * that cannot be said — it is not ready at `atMs`, the unit never cast it
 * before `atMs`, or it is a multi-charge interrupt that never ran out of
 * charges (ready since before its first logged cast). Triage 2026-09-29,
 * kick-priority F-P5 (ruling A′3). One predicate with the cooldown above:
 * the same cast list, cooldown, charge simulation and event reductions, so
 * the fact can never contradict the feasibility test.
 */
export function interruptReadySinceMs(
  unit: ICombatUnit,
  spellId: string,
  atMs: number,
): number | null {
  if (interruptCooldownRemainingMs(unit, spellId, atMs) > 0) return null;
  const castMs = interruptCastsUpTo(unit, spellId, atMs);
  if (!castMs.length) return null;
  const cooldownSeconds = interruptCooldownSeconds(spellId, unit) ?? 15;
  const charges = unitCooldownOf(unit, spellId)?.charges ?? 1;
  if (charges > 1) {
    // the last cast that left nothing in hand, and when a charge came back
    let since: number | null = null;
    for (const c of castMs) {
      const st = chargeStateAt(
        castMs.map((ms) => (ms - c) / 1000),
        cooldownSeconds,
        charges,
        0,
      );
      if (st.charges === 0) since = c + st.nextRecharge * 1000;
    }
    return since !== null && since <= atMs ? since : null;
  }
  return singleChargeReadyMs(
    unit,
    spellId,
    castMs[castMs.length - 1]!,
    atMs,
    cooldownSeconds,
  );
}

/**
 * Kit entries that interrupt only NON-PLAYER targets (tooltip: "interrupts and
 * silences non-player targets") — no arena coaching claim can rest on them.
 * Avenger's Shield 31935 sat before Rebuke 96231 in the kit's numeric order,
 * so every Protection Paladin's interrupt read as Avenger's Shield (talent
 * impact audit 2026-09-26). Registered in curatedIdRegistry.
 */
export const NON_PLAYER_INTERRUPT_IDS: ReadonlySet<string> = new Set([
  "31935", // Avenger's Shield
]);

/** The interrupt this unit has, or null (Holy Paladin, Preservation Evoker,
 * Restoration Druid, Mistweaver, Disc/Holy Priest, a Retribution Paladin who
 * did not take Rebuke …). Baseline before talent, talent before pet. */
export function interruptForUnit(unit: ICombatUnit): InterruptDef | null {
  const classId = Number(unit.class);
  const specId = String(unit.spec);
  const talents = unit.info?.talents;
  const hasTalentData = Array.isArray(talents) && talents.length > 0;
  let pet: InterruptDef | null = null;
  let talentPick: InterruptDef | null = null;
  for (const [spellId, e] of Object.entries(KIT)) {
    if (NON_PLAYER_INTERRUPT_IDS.has(spellId)) continue;
    if (
      e.classBaseline.includes(classId) ||
      e.specBaseline.includes(Number(specId))
    )
      return { spellId, name: e.name, confirmed: true };
    const node = e.talent[specId];
    if (node && !talentPick) {
      const taken = hasTalentData
        ? talents.some((t) => t.id1 === node.nodeId && t.id2 === node.entryId)
        : true; // no talent list in the log → tree availability (unconfirmed)
      if (taken)
        talentPick = { spellId, name: e.name, confirmed: hasTalentData };
    }
    if (e.pet && !pet) {
      const observed = (unit.petSpellCastEvents ?? []).some(
        (c) =>
          c.spellId === spellId &&
          c.logLine.event === LogEvent.SPELL_CAST_SUCCESS,
      );
      if (observed) pet = { spellId, name: e.name, confirmed: false };
    }
  }
  return talentPick ?? pet;
}

export interface IEnemyInterruptState {
  enemyName: string;
  spec: string;
  spellName: string;
  /** Seconds until the interrupt is available again; 0 = ready now. */
  cdRemainingSeconds: number;
  /** Whether the enemy has been observed casting this interrupt at or before atMs (GH #88, B8). */
  seen: boolean;
  /** Whether this interrupt is assumed ready (ready on cooldown, but never yet observed cast in this match at or before atMs). */
  assumedReady: boolean;
  /** The unit that casts this kick is inside a cast-blocking aura at atMs
   * (`castBlockingAuraAt`): off cooldown or not, the kick cannot be thrown
   * now (triage res-readiness F-C5b, ruling A′16). false when the round's
   * units were not handed in — unknown is never "blocked". */
  ccd: boolean;
}

/** Of several units (an owner's pets over a round), the one present at
 * `atMs`: not dead by then, and with the latest own event (cast, aura,
 * advanced sample) at or before it. Undefined when none was seen yet. */
function activeUnitAt(
  units: ReadonlyArray<ICombatUnit>,
  atMs: number,
): ICombatUnit | undefined {
  let best: ICombatUnit | undefined;
  let bestTs = -Infinity;
  for (const u of units) {
    if (isDeadAt(u, atMs)) continue;
    let last = -Infinity;
    for (const list of [
      u.spellCastEvents ?? [],
      u.auraEvents ?? [],
      u.advancedActions ?? [],
    ] as ReadonlyArray<ReadonlyArray<{ timestamp: number }>>)
      for (const e of list)
        if (e.timestamp <= atMs && e.timestamp > last) last = e.timestamp;
    if (last > bestTs) {
      bestTs = last;
      best = u;
    }
  }
  return best;
}

/** Is this state a kick the enemy could throw at that instant — off cooldown
 * and its caster able to cast. The one reading of "enemy interrupts UP"
 * (ruling A′16, 2026-09-30: "usable now", not "off cooldown"). */
export function isInterruptUsable(s: IEnemyInterruptState): boolean {
  return s.cdRemainingSeconds === 0 && !s.ccd;
}

/**
 * B128 / GH #88 (B8): for each enemy that has an interrupt, its ready/on-cooldown/assumed-ready state at atMs.
 * An interrupt is on cooldown when the enemy cast it within its cooldown window; otherwise it is ready.
 * If it has never yet been cast at or before atMs, it is marked as `assumedReady: true` and `seen: false`,
 * preventing consumers from falsely accusing the player of hardcasting in range when the enemy never kicks.
 *
 * Triage res-readiness F-C5 / F-C5b:
 *  - an enemy dead at atMs (`isDeadAt`, the one dead-at predicate) has no
 *    interrupt and is not in the result — 141470d0 7:21 listed Solar Beam for
 *    a Balance Druid dead for 52 s;
 *  - `ccd` says the kick's caster cannot cast at atMs. It needs the round's
 *    units (`allUnits`): the sources hostile to the kicker are the other
 *    side's players and their summons (`enemySourceIds`), and a pet kick
 *    (Spell Lock, Axe Toss) is asked of the pet(s) that cast it, not of the
 *    owner — a Warlock commands Spell Lock while stunned. The predicate is
 *    kick-eaten's (`castBlockingAuraAt`: hard CC stops every kick, a silence
 *    only a silenceable one, a school lockout none). Without `allUnits`
 *    nothing is `ccd`.
 */
export function computeEnemyInterruptAvailability(
  enemies: ICombatUnit[],
  atMs: number,
  allUnits?: ReadonlyArray<ICombatUnit>,
): IEnemyInterruptState[] {
  const result: IEnemyInterruptState[] = [];
  const enemyIds = new Set(enemies.map((e) => e.id));
  const hostileIds = allUnits
    ? enemySourceIds(
        allUnits.filter((u) => u.info && !enemyIds.has(u.id)),
        allUnits,
      )
    : undefined;
  for (const enemy of enemies) {
    if (isDeadAt(enemy, atMs)) continue;
    const def = interruptForUnit(enemy);
    if (!def) continue;
    // who throws it: the enemy, or the pet(s) seen casting a pet kick
    const petCasterIds = new Set(
      (enemy.petSpellCastEvents ?? [])
        .filter(
          (c) =>
            c.spellId === def.spellId &&
            c.logLine.event === LogEvent.SPELL_CAST_SUCCESS,
        )
        .map((c) => c.srcUnitId),
    );
    const ownCast = (enemy.spellCastEvents ?? []).some(
      (c) =>
        c.spellId === def.spellId &&
        c.logLine.event === LogEvent.SPELL_CAST_SUCCESS,
    );
    // the pet out at `atMs`: alive then, and the one last seen at or before
    // it — a pet that died earlier or was summoned later has no aura at
    // `atMs` and must not read "free" for the active one (codex review)
    const caster: ICombatUnit | undefined =
      petCasterIds.size > 0 && !ownCast
        ? activeUnitAt(
            (allUnits ?? []).filter((u) => petCasterIds.has(u.id)),
            atMs,
          )
        : enemy;
    const ccd =
      hostileIds !== undefined &&
      caster !== undefined &&
      castBlockingAuraAt(caster, hostileIds, atMs, def.spellId) !== undefined;
    // whole-second for the timeline's display; the exact value lives in
    // interruptCooldownRemainingMs (kick-priority reads that one — 0.4 s left
    // is NOT ready)
    const cdRemainingSeconds = Math.round(
      interruptCooldownRemainingMs(enemy, def.spellId, atMs) / 1000,
    );
    const seen = [
      ...(enemy.spellCastEvents ?? []),
      ...(enemy.petSpellCastEvents ?? []),
    ].some(
      (e) =>
        e.spellId === def.spellId &&
        e.logLine.event === LogEvent.SPELL_CAST_SUCCESS &&
        e.logLine.timestamp <= atMs,
    );
    result.push({
      enemyName: enemy.name,
      spec: specToString(enemy.spec),
      spellName: def.name,
      cdRemainingSeconds,
      seen,
      assumedReady: cdRemainingSeconds === 0 && !seen,
      ccd,
    });
  }
  return result;
}
