import { SPELL_CATEGORIES, SPELL_ICONS_GENERATED } from "@gladlog/analysis";

import type { ReportSource } from "./types";

export interface CastRow {
  t: number;
  spellId: number;
  spellName: string;
  targetName: string;
  byPet: boolean;
  /** Icon base name (from the mined spellIconsGenerated table); undefined when
   * the table has no entry → falls back to the first letter. */
  icon?: string;
}

/** Whether this aura belongs to the curated PvP category set (CC / root /
 * immunity / defensive CD / offensive CD / disarm / interrupt …). */
export function auraCategory(spellId: number): string | undefined {
  return SPELL_CATEGORIES[String(spellId)]?.type;
}

/** Whether this cast is a major / key cooldown (immunity, defensive CD,
 * offensive CD, disarm) — used to highlight it in the GCD lane. */
const MAJOR_CD_TYPES = new Set([
  "immunities",
  "buffs_defensive",
  "buffs_offensive",
  "disarms",
]);
export function isMajorCd(spellId: number): boolean {
  const c = auraCategory(spellId);
  return c != null && MAJOR_CD_TYPES.has(c);
}

export function deriveCasts(m: ReportSource, unitId: string): CastRow[] {
  const u = m.units[unitId];
  if (!u) return [];
  const row =
    (byPet: boolean) =>
    (e: (typeof u.casts)[number]): CastRow => ({
      t: e.timestamp,
      spellId: e.spellId,
      spellName: e.spellName,
      targetName: e.destName,
      byPet,
      icon: SPELL_ICONS_GENERATED[String(e.spellId)],
    });
  return [...u.casts.map(row(false)), ...u.petCasts.map(row(true))].sort(
    (a, b) => a.t - b.t,
  );
}

/** Deny list for auto-triggered casts / internal variants (every entry meets
 * all of: outside the table + high frequency across the user's 10-match corpus
 * + not a player keypress; for the "variant" entries the keypress id is already
 * in the keep set, so denying only de-duplicates and loses no information).
 * Rot defence = an evidence comment per entry + a corpus rescan (the
 * evidenceDist / dropped-list human review process). */
const AUTO_CAST_DENY: ReadonlySet<string> = new Set([
  "1217610", // Devour: DH hero-talent soul-fragment auto-trigger, x867, p50≈4s, user-reported
  "473662", // Consume: same ability, second id
  "341263", // Shadowy Apparition: priest apparition entity cast, x747, not a keypress
  "415388", // Recycled reuse: BM auto-trigger, x1030, 93% sub-GCD
  "393035", // Throw Glaive auto variant: the keypress version (Throw Glaive in the spellbook) is kept, x338
  "337819", // Throw Glaive auto variant: same as above, x311
  "1226019", // Reaping: DK hero-talent auto, x490
  "469270", // Wind of Ruin: warrior hero-talent auto, x258
  "228537", // Shattered Souls: DH soul-fragment generation event, x220
  "408385", // Expedition Strike: hero-talent auto follow-up, x316
  "1242174", // Death Coil variant: DK hero-talent auto, x157
  "1256581", // Merithra's Blessing: proc buff cast, x148
  "126664", // Charge displacement internal id: the keypress version 100 is kept, x173
]);
// Re-review record (2026-07-25, confirmed by the user): 155777 was once wrongly
// placed on the deny list — its official name is "Rejuvenation (Germination)",
// a genuine second Rejuvenation keypress granted by the Germination talent, not
// a duplicate instance. Lesson: look up the official name before adding an
// entry (anything with a talent name in parentheses is a talent-granted cast);
// talent-granted spell ids are NOT in talentIdMap (that holds talent NODE ids),
// so "not in the talent tree" is not grounds for calling a cast auto-triggered.

/** GCD floor (ms): at extreme haste the GCD is ≈ 0.75s, so consecutive casts of
 * the same spell closer than this cannot physically be player GCD behaviour
 * (they are resource procs / aura-tick style casts). */
const SUB_GCD_MS = 700;
/** Minimum sample size and sub-GCD interval ratio for calling a spell noise. */
const NOISE_MIN_CASTS = 4;
const NOISE_SUB_GCD_RATIO = 0.5;

/**
 * The cast stream under the GCD-lane definition (2026-07-25, from the user's
 * hands-on feedback; two gates):
 *  1) **Official-data gate**: the player keypress table (SkillLineAbility
 *     spellbook ∪ talent tree ∪ PvP talents, generated by genGcdSpells) ∪
 *     curated (an item-spell fallback). Triggered sub-spells / engine-internal
 *     ids (the DH Devour id pair, soul fragments, mage Snowdrift, the Hymn
 *     healing-effect id) are all outside the table — verified 13/13 on the
 *     known samples. A "has a SpellCooldowns row" predicate would miss Devour
 *     (triggered spells also have cooldown rows) and was rejected.
 *  2) **Physical layer**: consecutive casts of the same-named spell are mostly
 *     closer than the 700ms GCD floor (a hard game rule — at extreme haste the
 *     GCD is ≈ 750ms) → channel tick-by-tick CAST-event spam (the DH Devour id
 *     pair alternates, so only name-based aggregation catches it).
 *  3) Pet casts are kept only inside the curated PvP categories (so key events
 *     such as a felhunter's Spell Lock still show).
 */
export function filterGcdNoise(rows: CastRow[]): CastRow[] {
  const bySpell = new Map<string, number[]>();
  // Aggregate by name: dual-id abilities (Devour 1217610/473662) alternate, so
  // aggregating by id would miss them
  const keyOf = (r: CastRow) => `${r.spellName}:${r.byPet ? 1 : 0}`;
  for (const r of rows) {
    const arr = bySpell.get(keyOf(r)) ?? [];
    arr.push(r.t);
    bySpell.set(keyOf(r), arr);
  }
  const noisy = new Set<string>();
  for (const [key, ts] of bySpell) {
    if (ts.length < NOISE_MIN_CASTS) continue;
    let sub = 0;
    for (let i = 1; i < ts.length; i++)
      if (ts[i]! - ts[i - 1]! < SUB_GCD_MS) sub++;
    if (sub >= (ts.length - 1) * NOISE_SUB_GCD_RATIO) noisy.add(key);
  }
  return rows.filter((r) => {
    const sid = String(r.spellId);
    if (r.byPet) return !!SPELL_CATEGORIES[sid];
    if (AUTO_CAST_DENY.has(sid)) return false;
    if (noisy.has(keyOf(r))) return false; // the physical layer treats in-table and out-of-table alike
    return true; // keep by default when out of table (SkillLineAbility is incomplete; hard-dropping would kill real keypresses)
  });
}

/** The cast stream the GCD lane consumes = all casts minus GCD noise. */
export function deriveGcdCasts(m: ReportSource, unitId: string): CastRow[] {
  return filterGcdNoise(deriveCasts(m, unitId));
}
