// Stress-fixture smoke test: run the core derive functions over every
// dev/local/stress-*.json; exit non-zero if any of them throws or produces an
// empty summary. Pairs with the wild edge-case samples generated by
// make-report-fixture.mjs (CJK names, very long matches, shuffle rounds, no
// coordinates); it does not open a browser to verify the render layer.
//   npx tsx packages/desktop/scripts/smokeStressFixtures.ts
/* eslint-disable no-console */
import { readFileSync, readdirSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

import { deriveDeathRecaps } from "../src/renderer/src/report/derive/deathRecap";
import { deriveReplay } from "../src/renderer/src/report/derive/replay";
import { deriveStatsTable } from "../src/renderer/src/report/derive/statsTable";
import { deriveSummary } from "../src/renderer/src/report/derive/summary";
import { deriveTimeline } from "../src/renderer/src/report/derive/timeline";
import type { ReportSource } from "../src/renderer/src/report/derive/types";

const dir = join(__dirname, "..", "dev", "local");
if (!existsSync(dir)) {
  console.log("no dev/local — nothing to smoke");
  process.exit(0);
}
const files = readdirSync(dir).filter(
  (f) =>
    f.startsWith("stress-") && f.endsWith(".json") && f !== "stress-index.json",
);
let failed = 0;
for (const f of files) {
  try {
    const src = JSON.parse(readFileSync(join(dir, f), "utf-8")) as ReportSource;
    const summary = deriveSummary(src);
    const timeline = deriveTimeline(src);
    const replay = deriveReplay(src);
    const deaths = deriveDeathRecaps(src);
    const stats = deriveStatsTable(src);
    if (summary.length === 0) throw new Error("empty summary");
    console.log(
      `ok ${f}: summary=${summary.length} hpSeries=${timeline.series.length} adv=${timeline.hasAdvanced} replayTracks=${replay.tracks.length} deaths=${deaths.length} stats=${stats.length}`,
    );
  } catch (e) {
    failed++;
    console.error(
      `FAIL ${f}: ${String((e as Error)?.stack ?? e).slice(0, 300)}`,
    );
  }
}
process.exit(failed > 0 ? 1 : 0);
